In [1]:
import pandas as pd
import numpy as np

# 수도권역

In [2]:
dataset_seoul = pd.read_excel('car_seoul_2010.xlsx')

In [3]:
dataset_seoul

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"25,962","26,911","20,658","13,319","12,150","15,081","21,101","28,679",...,"71,164","71,471","69,306","63,100","53,207","44,400","42,824","39,551","31,336","21,912"
1,NaN,출구,"22,702","22,792","16,993","11,043","9,100","10,785","13,241","17,533",...,"68,846","72,283","73,643","68,835","60,067","49,844","46,478","44,207","37,562","27,655"
2,NaN,합계,"48,664","49,703","37,651","24,362","21,250","25,866","34,342","46,212",...,"140,010","143,754","142,949","131,935","113,274","94,244","89,302","83,758","68,898","49,567"
3,2010.01.02,입구,"13,714","8,432","5,835","5,255","6,871","12,208","21,561","30,350",...,"65,804","67,090","67,671","63,776","53,369","41,000","38,674","35,373","29,599","21,596"
4,NaN,출구,"18,239","10,714","7,077","5,599","5,788","8,931","15,399","23,740",...,"66,923","70,150","71,070","70,785","64,607","54,315","51,133","46,932","41,255","30,018"
5,NaN,합계,"31,953","19,146","12,912","10,854","12,659","21,139","36,960","54,090",...,"132,727","137,240","138,741","134,561","117,976","95,315","89,807","82,305","70,854","51,614"
6,2010.01.03,입구,"14,520","9,476","6,719","5,410","6,311","9,122","15,041","19,564",...,"63,841","65,725","65,360","59,226","49,002","41,103","43,203","37,946","28,942","20,482"
7,NaN,출구,"21,107","14,454","10,716","7,682","6,596","8,440","12,727","16,244",...,"66,590","69,006","70,181","64,618","57,892","48,964","46,988","43,693","34,386","26,595"
8,NaN,합계,"35,627","23,930","17,435","13,092","12,907","17,562","27,768","35,808",...,"130,431","134,731","135,541","123,844","106,894","90,067","90,191","81,639","63,328","47,077"
9,2010.01.04,입구,"11,803","7,682","5,862","5,519","8,621","20,547","39,248","32,311",...,"20,649","20,640","23,029","23,388","20,467","15,266","11,710","9,585","8,107","6,225"
10,NaN,출구,"16,621","10,230","7,775","5,538","6,148","10,273","20,086","23,704",...,"23,274","22,023","21,786","25,300","24,232","18,609","13,736","10,999","9,213","7,216"
11,NaN,합계,"28,424","17,912","13,637","11,057","14,769","30,820","59,334","56,015",...,"43,923","42,663","44,815","48,688","44,699","33,875","25,446","20,584","17,320","13,441"
12,2010.01.05,입구,"4,565","3,599","3,142","3,240","4,500","9,813","26,265","41,125",...,"50,786","49,983","48,534","50,513","49,917","40,317","30,680","25,412","20,250","15,005"
13,NaN,출구,"5,497","4,284","3,683","3,336","3,895","7,166","18,726","34,959",...,"49,519","51,388","50,799","51,518","53,269","47,019","34,703","28,635","23,349","17,549"
14,NaN,합계,"10,062","7,883","6,825","6,576","8,395","16,979","44,991","76,084",...,"100,305","101,371","99,333","102,031","103,186","87,336","65,383","54,047","43,599","32,554"
15,2010.01.06,입구,"10,419","7,249","5,648","5,115","6,514","13,796","39,866","65,401",...,"65,606","64,133","62,373","64,880","64,344","53,325","42,404","35,026","27,325","20,014"
16,NaN,출구,"12,491","8,948","6,462","5,327","5,839","10,517","28,733","53,972",...,"65,236","65,571","64,785","68,548","71,180","61,480","47,536","39,824","31,650","23,448"
17,NaN,합계,"22,910","16,197","12,110","10,442","12,353","24,313","68,599","119,373",...,"130,842","129,704","127,158","133,428","135,524","114,805","89,940","74,850","58,975","43,462"
18,2010.01.07,입구,"13,358","8,939","6,697","5,659","7,275","15,269","44,164","74,658",...,"68,739","68,866","68,753","70,270","68,310","56,039","44,474","38,120","30,471","22,301"
19,NaN,출구,"16,639","10,831","7,550","6,115","6,528","11,555","31,331","59,041",...,"68,602","68,478","71,248","73,690","76,308","66,563","52,041","43,575","35,443","26,324"
20,NaN,합계,"29,997","19,770","14,247","11,774","13,803","26,824","75,495","133,699",...,"137,341","137,344","140,001","143,960","144,618","122,602","96,515","81,695","65,914","48,625"
21,2010.01.08,입구,"14,995","9,918","7,227","6,157","7,708","16,103","45,863","76,618",...,"73,378","72,761","74,848","78,148","78,580","69,277","58,469","49,267","39,762","28,361"
22,NaN,출구,"18,296","12,425","8,328","6,681","7,087","12,595","33,889","61,657",...,"71,469","73,281","76,210","80,971","83,981","80,695","69,742","57,121","45,727","33,627"
23,NaN,합계,"33,291","22,343","15,555","12,838","14,795","28,698","79,752","138,275",...,"144,847","146,042","151,058","159,119","162,561","149,972","128,211","106,388","85,489","61,988"
24,2010.01.09,입구,"19,810","13,880","10,456","8,773","10,228","17,952","36,245","51,773",...,"72,767","73,718","75,064","73,163","65,296","53,929","42,297","36,775","29,942","21,783"
25,NaN,출구,"23,724","16,526","12,032","9,489","9,214","14,562","28,834","41,758",...,"70,347","72,244","75,208","74,790","73,461","65,588","48,673","41,130","35,243","25,587"
26,NaN,합계,"43,534","30,406","22,488","18,262","19,442","32,514","65,079","93,531",...,"143,114","145,962","150,272","147,953","138,757","119,517","90,970","77,905","65,185","47,370"
27,2010.01.10,입구,"14,905","10,033","7,153","5,931","6,575","10,597","18,626","23,834",...,"56,763","60,157","62,632","59,173","50,769","41,529","41,477","37,330","28,892","19,885"
28,NaN,출구,"17,854","12,179","8,490","6,674","6,297","8,920","15,070","18,614",...,"58,132","63,456","65,803","64,274","58,239","47,598","44,061","40,052","33,976","24,350"
29,NaN,합계,"32,759","22,212","15,643","12,605","12,872","19,517","33,696","42,448",...,"114,895","123,613","128,435","123,447","109,008","89,127","85,538","77,382","62,868","44,235"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"19,084","13,076","9,368","8,061","10,130","23,616","58,721","89,408",...,"78,551","78,164","79,264","82,855","79,407","62,212","48,740","43,974","37,215","28,421"
1066,NaN,출구,"24,042","16,729","11,322","8,851","9,184","17,690","43,745","72,538",...,"77,376","80,280","84,688","87,725","88,487","79,057","58,190","51,015","43,504","34,279"
1067,NaN,합계,"43,126","29,805","20,690","16,912","19,314","41,306","102,466","161,946",...,"155,927","158,444","163,952","170,580","167,894","141,269","106,930","94,989","80,719","62,700"
1068,2010.12.23,입구,"20,068","13,749","9,950","8,539","9,959","23,243","57,035","87,692",...,"79,392","79,117","79,372","83,703","77,700","61,342","50,916","45,071","37,861","29,658"
1069,NaN,출구,"25,205","17,133","11,878","9,229","9,170","17,781","43,456","71,520",...,"79,558","81,553","84,687","87,828","89,109","76,808","59,651","51,783","44,619","35,691"
1070,NaN,합계,"45,273","30,882","21,828","17,768","19,129","41,024","100,491","159,212",...,"158,950","160,670","164,059","171,531","166,809","138,150","110,567","96,854","82,480","65,349"
1071,2010.12.24,입구,"20,540","14,515","10,323","8,405","9,901","20,192","50,669","83,887",...,"80,340","81,810","86,479","92,287","89,787","79,602","70,778","57,048","46,307","34,231"
1072,NaN,출구,"26,188","18,044","12,501","9,387","9,331","15,698","38,526","68,669",...,"77,983","81,522","87,097","92,276","94,125","89,860","80,872","68,718","55,870","39,440"
1073,NaN,합계,"46,728","32,559","22,824","17,792","19,232","35,890","89,195","152,556",...,"158,323","163,332","173,576","184,563","183,912","169,462","151,650","125,766","102,177","73,671"
1074,2010.12.25,입구,"23,963","16,179","11,275","9,323","10,274","15,260","26,489","34,500",...,"67,635","69,062","69,840","66,123","55,295","42,761","39,267","38,452","32,254","24,814"
1075,NaN,출구,"27,282","18,244","12,492","9,461","9,384","11,437","19,135","25,223",...,"65,800","71,563","74,041","72,191","62,326","49,352","43,018","41,711","37,017","28,358"
1076,NaN,합계,"51,245","34,423","23,767","18,784","19,658","26,697","45,624","59,723",...,"133,435","140,625","143,881","138,314","117,621","92,113","82,285","80,163","69,271","53,172"
1077,2010.12.26,입구,"16,681","10,409","7,051","5,585","6,318","9,491","16,256","21,678",...,"66,446","67,606","67,022","61,600","50,138","44,068","44,795","40,345","29,641","22,168"
1078,NaN,출구,"19,989","12,671","8,543","6,434","6,247","7,883","13,188","16,577",...,"65,656","67,385","68,814","67,680","58,323","51,266","49,562","44,303","36,158","26,806"
1079,NaN,합계,"36,670","23,080","15,594","12,019","12,565","17,374","29,444","38,255",...,"132,102","134,991","135,836","129,280","108,461","95,334","94,357","84,648","65,799","48,974"
1080,2010.12.27,입구,"12,352","7,332","5,524","5,575","10,301","32,065","72,295","87,664",...,"69,685","69,020","70,363","71,409","67,574","53,005","41,660","36,869","29,756","21,545"
1081,NaN,출구,"16,587","10,352","6,884","5,698","7,186","18,583","48,539","72,823",...,"68,593","72,518","75,773","76,544","78,048","65,685","49,595","42,473","34,690","25,904"
1082,NaN,합계,"28,939","17,684","12,408","11,273","17,487","50,648","120,834","160,487",...,"138,278","141,538","146,136","147,953","145,622","118,690","91,255","79,342","64,446","47,449"
1083,2010.12.28,입구,"14,630","10,741","7,191","6,332","7,851","15,047","36,865","61,626",...,"61,611","61,625","62,255","63,306","60,084","44,306","35,802","32,260","27,149","20,963"
1084,NaN,출구,"18,453","13,437","8,274","6,547","7,505","11,851","27,320","51,317",...,"61,059","64,801","66,568","67,434","67,208","54,975","42,304","37,462","31,609","24,982"
1085,NaN,합계,"33,083","24,178","15,465","12,879","15,356","26,898","64,185","112,943",...,"122,670","126,426","128,823","130,740","127,292","99,281","78,106","69,722","58,758","45,945"
1086,2010.12.29,입구,"15,075","11,143","8,000","7,003","8,340","17,847","46,567","76,404",...,"78,137","76,945","77,810","80,450","75,388","57,595","45,461","39,419","33,069","25,364"
1087,NaN,출구,"18,902","13,839","9,838","7,690","7,779","13,639","34,523","61,727",...,"77,287","78,246","83,066","84,749","86,989","71,781","52,694","44,339","37,767","29,646"
1088,NaN,합계,"33,977","24,982","17,838","14,693","16,119","31,486","81,090","138,131",...,"155,424","155,191","160,876","165,199","162,377","129,376","98,155","83,758","70,836","55,010"
1089,2010.12.30,입구,"17,724","12,130","8,411","6,520","7,323","13,576","34,639","59,926",...,"68,128","67,462","67,458","69,940","65,671","49,609","39,336","35,600","31,256","24,449"
1090,NaN,출구,"20,023","15,096","10,583","7,069","7,367","10,693","25,077","48,772",...,"67,142","68,872","70,406","72,848","75,501","59,355","44,878","39,617","35,641","28,217"
1091,NaN,합계,"37,747","27,226","18,994","13,589","14,690","24,269","59,716","108,698",...,"135,270","136,334","137,864","142,788","141,172","108,964","84,214","75,217","66,897","52,666"
1092,2010.12.31,입구,"17,955","13,150","9,823","8,006","8,854","15,544","38,725","68,682",...,"77,271","81,402","85,152","87,255","80,994","71,254","62,399","54,369","45,374","31,879"
1093,NaN,출구,"21,403","15,479","11,325","8,893","8,430","12,462","28,335","55,460",...,"72,943","76,749","83,937","86,876","86,460","78,432","68,524","56,737","46,234","33,205"
1094,NaN,합계,"39,358","28,629","21,148","16,899","17,284","28,006","67,060","124,142",...,"150,214","158,151","169,089","174,131","167,454","149,686","130,923","111,106","91,608","65,084"

In [4]:
imsi_day = pd.DataFrame(dataset_seoul['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_seoul = dataset_seoul[(dataset_seoul.입출구 == '합계')]
dataset_seoul = dataset_seoul.reset_index()
del dataset_seoul['index']

In [5]:
del dataset_seoul['일자']
del dataset_seoul['입출구']

In [6]:
dataset_seoul = pd.concat([imsi_day, dataset_seoul], axis = 1)

In [7]:
day_time = []

for i in range(len(dataset_seoul)):
    for j in range(1,25):
        day_time.append(dataset_seoul.iloc[i][0] +'.' + dataset_seoul.columns[j])

In [8]:
car_time = []

for i in range(len(dataset_seoul)):
    for j in range(1,25):
        car_time.append(dataset_seoul.iloc[i][j])

In [9]:
dataset_seoul = pd.DataFrame({'시간' : day_time, '서울 교통량' : car_time })

In [10]:
dataset_seoul = dataset_seoul.set_index('시간')

In [11]:
dataset_seoul

                 서울 교통량
시간
2010.01.01.00시   48,664
2010.01.01.01시   49,703
2010.01.01.02시   37,651
2010.01.01.03시   24,362
2010.01.01.04시   21,250
2010.01.01.05시   25,866
2010.01.01.06시   34,342
2010.01.01.07시   46,212
2010.01.01.08시   61,214
2010.01.01.09시   81,427
2010.01.01.10시  112,769
2010.01.01.11시  139,873
2010.01.01.12시  144,359
2010.01.01.13시  139,629
2010.01.01.14시  140,010
2010.01.01.15시  143,754
2010.01.01.16시  142,949
2010.01.01.17시  131,935
2010.01.01.18시  113,274
2010.01.01.19시   94,244
2010.01.01.20시   89,302
2010.01.01.21시   83,758
2010.01.01.22시   68,898
2010.01.01.23시   49,567
2010.01.02.00시   31,953
2010.01.02.01시   19,146
2010.01.02.02시   12,912
2010.01.02.03시   10,854
2010.01.02.04시   12,659
2010.01.02.05시   21,139
...                 ...
2010.12.30.18시  141,172
2010.12.30.19시  108,964
2010.12.30.20시   84,214
2010.12.30.21시   75,217
2010.12.30.22시   66,897
2010.12.30.23시   52,666
2010.12.31.00시   39,358
2010.12.31.01시   28,629
2010.12.31.02시   21,148
2010.12.31.03시   16,899
2010.12.31.04시   17,284
2010.12.31.05시   28,006
2010.12.31.06시   67,060
2010.12.31.07시  124,142
2010.12.31.08시  138,612
2010.12.31.09시  124,551
2010.12.31.10시  131,012
2010.12.31.11시  132,699
2010.12.31.12시  131,153
2010.12.31.13시  139,056
2010.12.31.14시  150,214
2010.12.31.15시  158,151
2010.12.31.16시  169,089
2010.12.31.17시  174,131
2010.12.31.18시  167,454
2010.12.31.19시  149,686
2010.12.31.20시  130,923
2010.12.31.21시  111,106
2010.12.31.22시   91,608
2010.12.31.23시   65,084

[8760 rows x 1 columns]

# 강원권역

In [12]:
import pandas as pd
import numpy as np

In [13]:
dataset_gangwon = pd.read_excel('car_gangwon_2010.xlsx')

In [14]:
dataset_gangwon

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"3,097","2,990","2,767","3,003","3,355","3,258","3,845","3,959",...,"16,076","16,021","16,327","15,026","12,148","9,305","7,329","5,406","4,091","2,656"
1,NaN,출구,"6,532","5,900","5,529","5,940","5,821","6,177","5,651","6,955",...,"16,638","16,948","17,646","16,621","13,888","10,930","7,847","5,813","4,407","3,067"
2,NaN,합계,"9,629","8,890","8,296","8,943","9,176","9,435","9,496","10,914",...,"32,714","32,969","33,973","31,647","26,036","20,235","15,176","11,219","8,498","5,723"
3,2010.01.02,입구,"1,809","1,365",972,930,"1,061","1,366","1,872","3,096",...,"15,531","15,100","14,625","12,954","10,510","7,760","6,290","5,005","4,304","3,369"
4,NaN,출구,"1,920","1,381","1,003",785,774,910,"1,606","2,767",...,"14,820","15,111","13,924","12,126","10,646","8,530","6,596","4,940","3,721","2,878"
5,NaN,합계,"3,729","2,746","1,975","1,715","1,835","2,276","3,478","5,863",...,"30,351","30,211","28,549","25,080","21,156","16,290","12,886","9,945","8,025","6,247"
6,2010.01.03,입구,"2,117","1,584",902,963,"1,080","1,246","1,651","2,805",...,"13,334","12,478","11,036","9,279","6,925","5,324","4,930","3,803","2,815","1,888"
7,NaN,출구,"2,113","1,301",805,543,512,597,"1,019","1,729",...,"10,786","10,765","10,739","9,591","7,746","5,503","4,567","3,960","3,156","2,138"
8,NaN,합계,"4,230","2,885","1,707","1,506","1,592","1,843","2,670","4,534",...,"24,120","23,243","21,775","18,870","14,671","10,827","9,497","7,763","5,971","4,026"
9,2010.01.04,입구,"1,162",785,611,720,"1,000","1,849","3,174","4,938",...,"3,054","2,913","2,893","2,779","2,324","1,511","1,164",818,632,465
10,NaN,출구,"1,458",915,616,542,558,737,"1,553","3,211",...,"3,340","3,295","3,697","3,309","3,198","2,372","1,630","1,140",851,629
11,NaN,합계,"2,620","1,700","1,227","1,262","1,558","2,586","4,727","8,149",...,"6,394","6,208","6,590","6,088","5,522","3,883","2,794","1,958","1,483","1,094"
12,2010.01.05,입구,364,300,249,271,316,475,844,"2,018",...,"5,104","4,796","4,433","4,594","4,090","2,605","1,931","1,550","1,149",754
13,NaN,출구,477,367,318,323,258,326,587,"1,444",...,"4,737","4,722","4,530","4,464","4,318","3,164","2,151","1,749","1,413","1,058"
14,NaN,합계,841,667,567,594,574,801,"1,431","3,462",...,"9,841","9,518","8,963","9,058","8,408","5,769","4,082","3,299","2,562","1,812"
15,2010.01.06,입구,651,409,372,378,485,789,"1,343","2,930",...,"6,055","6,049","6,112","5,854","5,394","3,449","2,555","2,086","1,604","1,141"
16,NaN,출구,750,559,413,362,381,459,953,"2,309",...,"6,286","6,038","5,933","5,759","5,535","4,062","2,910","2,327","1,998","1,376"
17,NaN,합계,"1,401",968,785,740,866,"1,248","2,296","5,239",...,"12,341","12,087","12,045","11,613","10,929","7,511","5,465","4,413","3,602","2,517"
18,2010.01.07,입구,805,521,448,465,596,936,"1,669","3,392",...,"7,037","6,844","6,925","6,673","6,032","3,927","2,974","2,379","1,785","1,291"
19,NaN,출구,"1,010",706,511,438,475,548,"1,121","2,998",...,"6,819","6,593","6,508","6,260","6,135","4,528","3,311","2,599","2,192","1,654"
20,NaN,합계,"1,815","1,227",959,903,"1,071","1,484","2,790","6,390",...,"13,856","13,437","13,433","12,933","12,167","8,455","6,285","4,978","3,977","2,945"
21,2010.01.08,입구,920,603,460,486,684,"1,010","1,742","3,412",...,"7,858","8,188","8,522","8,656","8,765","6,197","4,435","3,240","2,539","1,623"
22,NaN,출구,"1,153",795,532,458,450,650,"1,196","2,844",...,"7,970","8,019","8,204","8,535","8,642","7,369","6,055","5,498","4,914","3,794"
23,NaN,합계,"2,073","1,398",992,944,"1,134","1,660","2,938","6,256",...,"15,828","16,207","16,726","17,191","17,407","13,566","10,490","8,738","7,453","5,417"
24,2010.01.09,입구,"1,212",861,683,723,"1,038","1,247","1,915","3,100",...,"10,228","10,233","10,315","10,107","8,150","5,766","4,670","3,596","2,496","1,748"
25,NaN,출구,"2,550","1,595",956,740,710,892,"1,756","3,613",...,"10,695","10,294","10,283","10,261","8,784","6,839","5,709","4,860","3,774","2,612"
26,NaN,합계,"3,762","2,456","1,639","1,463","1,748","2,139","3,671","6,713",...,"20,923","20,527","20,598","20,368","16,934","12,605","10,379","8,456","6,270","4,360"
27,2010.01.10,입구,"1,211",955,658,685,923,"1,011","1,279","2,167",...,"11,726","11,412","11,198","10,403","7,779","5,909","5,165","3,676","2,545","1,770"
28,NaN,출구,"1,639","1,154",743,548,531,574,"1,034","2,154",...,"8,359","8,761","8,804","8,916","7,230","5,400","4,553","3,830","2,884","2,163"
29,NaN,합계,"2,850","2,109","1,401","1,233","1,454","1,585","2,313","4,321",...,"20,085","20,173","20,002","19,319","15,009","11,309","9,718","7,506","5,429","3,933"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"1,121",793,642,748,951,"1,540","2,603","4,740",...,"9,262","9,293","9,486","8,838","7,442","4,917","3,666","3,160","2,219","1,689"
1066,NaN,출구,"1,496",937,687,556,667,988,"2,200","4,423",...,"8,242","8,401","7,961","7,956","7,453","5,328","3,796","3,448","2,719","1,990"
1067,NaN,합계,"2,617","1,730","1,329","1,304","1,618","2,528","4,803","9,163",...,"17,504","17,694","17,447","16,794","14,895","10,245","7,462","6,608","4,938","3,679"
1068,2010.12.23,입구,"1,142",766,584,736,949,"1,532","2,608","4,612",...,"9,388","9,355","9,052","8,715","7,368","4,993","3,883","3,135","2,317","1,726"
1069,NaN,출구,"1,448","1,011",709,623,650,929,"2,038","4,388",...,"8,475","8,542","8,201","7,762","7,399","5,500","4,199","3,610","3,036","2,263"
1070,NaN,합계,"2,590","1,777","1,293","1,359","1,599","2,461","4,646","9,000",...,"17,863","17,897","17,253","16,477","14,767","10,493","8,082","6,745","5,353","3,989"
1071,2010.12.24,입구,"1,191",845,668,787,901,"1,413","2,305","4,208",...,"9,675","9,868","10,057","10,658","11,567","8,674","6,174","4,268","3,204","2,496"
1072,NaN,출구,"1,548","1,121",756,608,592,848,"1,859","3,882",...,"9,518","9,798","9,950","10,343","11,144","10,364","8,172","7,724","8,036","6,592"
1073,NaN,합계,"2,739","1,966","1,424","1,395","1,493","2,261","4,164","8,090",...,"19,193","19,666","20,007","21,001","22,711","19,038","14,346","11,992","11,240","9,088"
1074,2010.12.25,입구,"1,617","1,108",907,961,"1,040","1,243","1,641","2,710",...,"12,322","12,376","12,230","11,472","9,135","6,897","5,535","4,417","3,092","2,104"
1075,NaN,출구,"4,821","3,432","1,926","1,256","1,037","1,300","2,237","3,758",...,"12,828","12,908","12,244","11,258","9,210","6,635","5,403","4,592","3,576","2,603"
1076,NaN,합계,"6,438","4,540","2,833","2,217","2,077","2,543","3,878","6,468",...,"25,150","25,284","24,474","22,730","18,345","13,532","10,938","9,009","6,668","4,707"
1077,2010.12.26,입구,"1,357","1,036",821,880,887,993,"1,420","2,365",...,"14,736","14,650","12,210","9,952","7,169","5,770","5,107","3,774","2,568","1,935"
1078,NaN,출구,"1,874","1,187",783,585,534,635,"1,142","2,028",...,"11,286","11,440","11,031","10,157","7,778","5,768","4,714","4,241","3,171","2,372"
1079,NaN,합계,"3,231","2,223","1,604","1,465","1,421","1,628","2,562","4,393",...,"26,022","26,090","23,241","20,109","14,947","11,538","9,821","8,015","5,739","4,307"
1080,2010.12.27,입구,"1,050",670,540,698,"1,037","1,953","3,282","5,394",...,"8,868","8,865","8,555","8,033","6,653","4,457","3,338","2,618","1,885","1,376"
1081,NaN,출구,"1,657",886,568,467,505,942,"2,597","5,570",...,"8,228","8,167","8,062","8,003","7,362","5,248","3,716","2,995","2,356","1,797"
1082,NaN,합계,"2,707","1,556","1,108","1,165","1,542","2,895","5,879","10,964",...,"17,096","17,032","16,617","16,036","14,015","9,705","7,054","5,613","4,241","3,173"
1083,2010.12.28,입구,961,676,604,601,722,"1,037","1,815","3,516",...,"8,037","7,567","7,223","7,131","5,898","3,928","3,032","2,404","1,791","1,330"
1084,NaN,출구,"1,286",838,624,538,454,701,"1,261","2,802",...,"6,914","7,355","7,203","7,048","6,413","4,844","3,450","2,788","2,148","1,757"
1085,NaN,합계,"2,247","1,514","1,228","1,139","1,176","1,738","3,076","6,318",...,"14,951","14,922","14,426","14,179","12,311","8,772","6,482","5,192","3,939","3,087"
1086,2010.12.29,입구,994,658,536,622,726,"1,008","1,989","3,809",...,"8,932","9,177","9,029","8,759","7,177","4,839","3,655","2,871","2,146","1,589"
1087,NaN,출구,"1,205",857,599,526,534,669,"1,461","3,347",...,"8,810","8,748","8,515","8,436","7,596","5,410","3,924","3,372","2,812","2,081"
1088,NaN,합계,"2,199","1,515","1,135","1,148","1,260","1,677","3,450","7,156",...,"17,742","17,925","17,544","17,195","14,773","10,249","7,579","6,243","4,958","3,670"
1089,2010.12.30,입구,"1,126",736,635,537,624,859,"1,573","3,190",...,"7,778","7,875","7,535","7,295","6,198","4,121","3,124","2,443","1,936","1,420"
1090,NaN,출구,"1,471",868,783,616,546,674,"1,013","2,414",...,"7,825","7,910","7,649","7,454","6,941","5,134","3,780","3,191","2,628","2,088"
1091,NaN,합계,"2,597","1,604","1,418","1,153","1,170","1,533","2,586","5,604",...,"15,603","15,785","15,184","14,749","13,139","9,255","6,904","5,634","4,564","3,508"
1092,2010.12.31,입구,"1,030",750,606,687,747,"1,013","1,648","3,284",...,"10,535","10,732","11,547","11,627","11,195","8,685","6,698","5,239","4,084","3,162"
1093,NaN,출구,"1,483","1,034",731,576,606,684,"1,339","2,979",...,"11,162","11,642","12,559","13,076","12,749","11,843","10,386","9,733","8,787","7,791"
1094,NaN,합계,"2,513","1,784","1,337","1,263","1,353","1,697","2,987","6,263",...,"21,697","22,374","24,106","24,703","23,944","20,528","17,084","14,972","12,871","10,953"

In [15]:
imsi_day = pd.DataFrame(dataset_gangwon['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_gangwon = dataset_gangwon[(dataset_gangwon.입출구 == '합계')]
dataset_gangwon = dataset_gangwon.reset_index()
del dataset_gangwon['index']

In [16]:
del dataset_gangwon['일자']
del dataset_gangwon['입출구']

In [17]:
dataset_gangwon = pd.concat([imsi_day, dataset_gangwon], axis = 1)

In [18]:
day_time = []

for i in range(len(dataset_gangwon)):
    for j in range(1,25):
        day_time.append(dataset_gangwon.iloc[i][0] +'.' + dataset_gangwon.columns[j])

In [19]:
car_time = []

for i in range(len(dataset_gangwon)):
    for j in range(1,25):
        car_time.append(dataset_gangwon.iloc[i][j])

In [20]:
dataset_gangwon = pd.DataFrame({'시간' : day_time, '강원 교통량' : car_time })

In [21]:
dataset_gangwon = dataset_gangwon.set_index('시간')

In [22]:
dataset_gangwon

                강원 교통량
시간
2010.01.01.00시   9,629
2010.01.01.01시   8,890
2010.01.01.02시   8,296
2010.01.01.03시   8,943
2010.01.01.04시   9,176
2010.01.01.05시   9,435
2010.01.01.06시   9,496
2010.01.01.07시  10,914
2010.01.01.08시  17,646
2010.01.01.09시  20,077
2010.01.01.10시  26,014
2010.01.01.11시  30,977
2010.01.01.12시  31,688
2010.01.01.13시  32,104
2010.01.01.14시  32,714
2010.01.01.15시  32,969
2010.01.01.16시  33,973
2010.01.01.17시  31,647
2010.01.01.18시  26,036
2010.01.01.19시  20,235
2010.01.01.20시  15,176
2010.01.01.21시  11,219
2010.01.01.22시   8,498
2010.01.01.23시   5,723
2010.01.02.00시   3,729
2010.01.02.01시   2,746
2010.01.02.02시   1,975
2010.01.02.03시   1,715
2010.01.02.04시   1,835
2010.01.02.05시   2,276
...                ...
2010.12.30.18시  13,139
2010.12.30.19시   9,255
2010.12.30.20시   6,904
2010.12.30.21시   5,634
2010.12.30.22시   4,564
2010.12.30.23시   3,508
2010.12.31.00시   2,513
2010.12.31.01시   1,784
2010.12.31.02시   1,337
2010.12.31.03시   1,263
2010.12.31.04시   1,353
2010.12.31.05시   1,697
2010.12.31.06시   2,987
2010.12.31.07시   6,263
2010.12.31.08시  10,569
2010.12.31.09시  10,884
2010.12.31.10시  13,542
2010.12.31.11시  16,364
2010.12.31.12시  17,700
2010.12.31.13시  19,902
2010.12.31.14시  21,697
2010.12.31.15시  22,374
2010.12.31.16시  24,106
2010.12.31.17시  24,703
2010.12.31.18시  23,944
2010.12.31.19시  20,528
2010.12.31.20시  17,084
2010.12.31.21시  14,972
2010.12.31.22시  12,871
2010.12.31.23시  10,953

[8760 rows x 1 columns]

# 충청권역

In [23]:
dataset_chungcheong = pd.read_excel('car_chungcheong_2010.xlsx')

In [24]:
dataset_chungcheong

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"3,853","3,957","2,755","2,363","2,206","2,438","3,273","4,973",...,"20,079","20,173","18,827","16,114","12,827","10,003","8,778","7,456","5,005","3,125"
1,NaN,출구,"5,315","4,286","3,558","2,983","2,757","3,165","3,712","4,411",...,"18,628","19,613","19,786","20,124","17,862","13,356","10,635","8,692","6,824","4,745"
2,NaN,합계,"9,168","8,243","6,313","5,346","4,963","5,603","6,985","9,384",...,"38,707","39,786","38,613","36,238","30,689","23,359","19,413","16,148","11,829","7,870"
3,2010.01.02,입구,"2,027","1,316",993,982,"1,410","2,129","3,705","6,195",...,"21,217","20,679","19,459","17,031","13,157","9,736","8,733","7,296","5,121","3,508"
4,NaN,출구,"3,220","2,110","1,307",974,978,"1,528","2,925","5,037",...,"18,715","19,728","20,685","20,176","17,596","13,443","10,912","8,898","6,928","4,954"
5,NaN,합계,"5,247","3,426","2,300","1,956","2,388","3,657","6,630","11,232",...,"39,932","40,407","40,144","37,207","30,753","23,179","19,645","16,194","12,049","8,462"
6,2010.01.03,입구,"2,285","1,464","1,105","1,044","1,197","1,591","2,665","4,793",...,"18,628","18,203","16,448","14,188","11,172","9,556","8,827","7,532","5,275","3,472"
7,NaN,출구,"3,418","2,370","1,545","1,148","1,018","1,258","2,267","3,816",...,"17,057","18,278","20,503","19,851","17,579","13,780","11,806","10,470","8,468","5,823"
8,NaN,합계,"5,703","3,834","2,650","2,192","2,215","2,849","4,932","8,609",...,"35,685","36,481","36,951","34,039","28,751","23,336","20,633","18,002","13,743","9,295"
9,2010.01.04,입구,"2,197","1,284","1,123","1,602","2,606","5,079","9,692","16,609",...,"7,507","7,886","8,061","8,589","9,062","5,692","3,929","3,008","2,323","1,588"
10,NaN,출구,"3,784","2,105","1,410","1,287","1,287","2,140","5,201","11,429",...,"8,804","9,043","9,775","9,825","10,936","7,706","5,065","3,849","2,965","2,350"
11,NaN,합계,"5,981","3,389","2,533","2,889","3,893","7,219","14,893","28,038",...,"16,311","16,929","17,836","18,414","19,998","13,398","8,994","6,857","5,288","3,938"
12,2010.01.05,입구,"1,121",970,986,"1,006","1,449","2,004","3,913","10,224",...,"12,168","11,834","11,943","11,972","12,866","8,443","6,128","4,891","3,458","2,427"
13,NaN,출구,"1,594","1,138","1,074",875,936,"1,291","2,563","7,828",...,"11,856","12,397","12,075","12,228","13,896","10,231","7,059","5,728","4,318","3,321"
14,NaN,합계,"2,715","2,108","2,060","1,881","2,385","3,295","6,476","18,052",...,"24,024","24,231","24,018","24,200","26,762","18,674","13,187","10,619","7,776","5,748"
15,2010.01.06,입구,"1,742","1,325","1,283","1,356","1,903","3,000","5,432","12,999",...,"15,613","15,552","15,196","15,484","15,605","10,199","7,478","6,064","4,387","2,952"
16,NaN,출구,"2,490","1,773","1,344","1,094","1,141","1,637","3,870","10,557",...,"14,850","15,149","14,683","15,158","17,043","12,487","8,422","7,070","5,536","4,140"
17,NaN,합계,"4,232","3,098","2,627","2,450","3,044","4,637","9,302","23,556",...,"30,463","30,701","29,879","30,642","32,648","22,686","15,900","13,134","9,923","7,092"
18,2010.01.07,입구,"2,086","1,469","1,342","1,488","2,119","3,274","5,950","13,761",...,"16,483","16,898","16,671","16,988","16,511","10,994","8,250","6,510","4,814","3,324"
19,NaN,출구,"3,047","2,156","1,509","1,233","1,248","1,725","4,181","11,591",...,"15,727","15,675","15,506","16,418","18,039","12,848","8,863","7,603","6,035","4,298"
20,NaN,합계,"5,133","3,625","2,851","2,721","3,367","4,999","10,131","25,352",...,"32,210","32,573","32,177","33,406","34,550","23,842","17,113","14,113","10,849","7,622"
21,2010.01.08,입구,"2,133","1,590","1,395","1,540","2,154","3,353","5,855","13,639",...,"18,423","18,929","19,279","21,109","23,365","16,687","11,967","9,235","6,619","4,242"
22,NaN,출구,"3,250","2,260","1,560","1,294","1,229","1,926","4,430","11,252",...,"16,779","16,712","17,496","18,827","22,062","18,569","13,285","10,552","8,656","5,982"
23,NaN,합계,"5,383","3,850","2,955","2,834","3,383","5,279","10,285","24,891",...,"35,202","35,641","36,775","39,936","45,427","35,256","25,252","19,787","15,275","10,224"
24,2010.01.09,입구,"2,807","2,042","1,688","1,738","2,248","3,454","5,431","9,383",...,"19,734","20,453","20,205","19,054","15,779","10,951","9,014","7,496","5,426","3,615"
25,NaN,출구,"4,260","3,060","2,045","1,593","1,520","1,977","4,030","7,768",...,"17,253","18,657","19,342","20,295","18,831","13,973","11,229","9,395","7,227","5,108"
26,NaN,합계,"7,067","5,102","3,733","3,331","3,768","5,431","9,461","17,151",...,"36,987","39,110","39,547","39,349","34,610","24,924","20,243","16,891","12,653","8,723"
27,2010.01.10,입구,"2,476","1,660","1,208","1,051","1,199","1,920","3,111","5,053",...,"17,667","18,082","16,500","15,063","12,051","9,723","8,951","7,192","5,005","3,182"
28,NaN,출구,"3,450","2,341","1,598","1,192","1,024","1,344","2,476","4,224",...,"14,284","15,686","17,244","17,712","15,469","12,421","11,157","9,835","7,789","5,460"
29,NaN,합계,"5,926","4,001","2,806","2,243","2,223","3,264","5,587","9,277",...,"31,951","33,768","33,744","32,775","27,520","22,144","20,108","17,027","12,794","8,642"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"2,867","2,157","1,758","1,875","2,598","4,347","7,958","17,262",...,"20,259","20,686","21,151","21,805","19,905","12,922","9,665","8,366","6,182","4,585"
1066,NaN,출구,"4,076","2,750","1,977","1,493","1,543","2,513","6,214","14,637",...,"18,560","18,830","18,869","20,391","21,903","15,046","10,056","8,961","7,176","5,530"
1067,NaN,합계,"6,943","4,907","3,735","3,368","4,141","6,860","14,172","31,899",...,"38,819","39,516","40,020","42,196","41,808","27,968","19,721","17,327","13,358","10,115"
1068,2010.12.23,입구,"2,993","2,075","1,810","1,956","2,667","4,241","7,899","17,294",...,"20,146","20,858","21,068","21,618","19,617","13,183","9,816","8,492","6,459","4,550"
1069,NaN,출구,"4,039","2,799","1,952","1,523","1,491","2,571","6,300","14,442",...,"18,851","18,600","18,609","19,957","21,377","14,833","10,498","8,995","7,385","5,758"
1070,NaN,합계,"7,032","4,874","3,762","3,479","4,158","6,812","14,199","31,736",...,"38,997","39,458","39,677","41,575","40,994","28,016","20,314","17,487","13,844","10,308"
1071,2010.12.24,입구,"3,151","2,128","1,822","1,929","2,548","3,918","7,283","16,223",...,"20,911","22,033","23,572","26,802","29,464","21,984","15,349","11,173","7,774","5,208"
1072,NaN,출구,"4,371","2,860","1,971","1,592","1,537","2,305","5,416","13,315",...,"18,201","18,781","19,624","21,779","25,627","22,920","17,617","13,976","10,838","7,982"
1073,NaN,합계,"7,522","4,988","3,793","3,521","4,085","6,223","12,699","29,538",...,"39,112","40,814","43,196","48,581","55,091","44,904","32,966","25,149","18,612","13,190"
1074,2010.12.25,입구,"3,508","2,440","1,781","1,583","1,925","2,534","4,356","6,928",...,"19,148","19,463","18,311","16,529","12,767","9,605","8,099","6,725","4,697","3,178"
1075,NaN,출구,"5,515","3,603","2,380","1,761","1,554","1,862","3,133","5,592",...,"17,296","17,997","18,466","17,819","15,381","11,657","9,219","8,588","6,664","4,760"
1076,NaN,합계,"9,023","6,043","4,161","3,344","3,479","4,396","7,489","12,520",...,"36,444","37,460","36,777","34,348","28,148","21,262","17,318","15,313","11,361","7,938"
1077,2010.12.26,입구,"2,150","1,371",915,870,969,"1,510","2,519","4,403",...,"20,392","20,046","17,909","14,711","10,626","8,570","7,477","6,043","4,289","3,281"
1078,NaN,출구,"3,385","2,215","1,402",999,880,"1,230","2,113","3,791",...,"14,704","15,532","15,775","18,336","18,624","15,042","11,377","9,412","7,597","5,538"
1079,NaN,합계,"5,535","3,586","2,317","1,869","1,849","2,740","4,632","8,194",...,"35,096","35,578","33,684","33,047","29,250","23,612","18,854","15,455","11,886","8,819"
1080,2010.12.27,입구,"1,888","1,297","1,167","1,250","2,434","4,442","8,775","17,411",...,"17,506","17,527","16,613","16,743","15,728","10,332","7,940","6,770","5,018","3,434"
1081,NaN,출구,"4,014","2,329","1,539","1,179","1,202","2,716","7,256","15,992",...,"16,740","16,798","16,771","17,028","18,053","12,565","8,942","7,703","6,264","4,694"
1082,NaN,합계,"5,902","3,626","2,706","2,429","3,636","7,158","16,031","33,403",...,"34,246","34,325","33,384","33,771","33,781","22,897","16,882","14,473","11,282","8,128"
1083,2010.12.28,입구,"2,435","1,758","1,676","1,813","2,318","3,624","6,437","15,627",...,"15,945","15,885","15,729","15,498","14,471","10,457","7,955","6,906","5,317","3,554"
1084,NaN,출구,"3,455","2,398","1,803","1,330","1,332","1,987","4,211","11,602",...,"16,188","16,335","15,756","15,343","15,572","14,726","10,821","7,879","6,244","4,565"
1085,NaN,합계,"5,890","4,156","3,479","3,143","3,650","5,611","10,648","27,229",...,"32,133","32,220","31,485","30,841","30,043","25,183","18,776","14,785","11,561","8,119"
1086,2010.12.29,입구,"2,255","1,735","1,551","1,711","2,022","3,216","5,842","14,074",...,"19,212","19,875","19,237","19,532","17,728","11,753","8,834","7,455","5,434","3,669"
1087,NaN,출구,"3,149","2,325","1,678","1,352","1,286","1,927","4,158","11,145",...,"17,824","17,980","17,745","18,529","19,657","13,720","9,651","8,035","6,792","4,923"
1088,NaN,합계,"5,404","4,060","3,229","3,063","3,308","5,143","10,000","25,219",...,"37,036","37,855","36,982","38,061","37,385","25,473","18,485","15,490","12,226","8,592"
1089,2010.12.30,입구,"2,626","2,093","1,707","1,744","1,917","2,945","5,623","14,083",...,"16,852","17,035","17,036","16,816","15,784","10,410","7,803","6,434","4,856","3,338"
1090,NaN,출구,"3,421","2,459","2,228","1,636","1,375","1,718","3,565","10,234",...,"15,259","15,896","16,430","16,433","17,213","12,751","8,992","7,119","5,795","4,259"
1091,NaN,합계,"6,047","4,552","3,935","3,380","3,292","4,663","9,188","24,317",...,"32,111","32,931","33,466","33,249","32,997","23,161","16,795","13,553","10,651","7,597"
1092,2010.12.31,입구,"2,429","1,802","1,556","1,626","2,077","2,766","5,271","12,990",...,"21,480","22,657","23,614","24,150","23,126","17,133","13,042","9,995","7,215","4,764"
1093,NaN,출구,"3,302","2,288","1,669","1,370","1,359","1,817","3,654","10,300",...,"17,292","18,618","20,275","21,934","22,974","19,682","15,936","13,271","10,608","7,410"
1094,NaN,합계,"5,731","4,090","3,225","2,996","3,436","4,583","8,925","23,290",...,"38,772","41,275","43,889","46,084","46,100","36,815","28,978","23,266","17,823","12,174"

In [25]:
imsi_day = pd.DataFrame(dataset_chungcheong['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_chungcheong = dataset_chungcheong[(dataset_chungcheong.입출구 == '합계')]
dataset_chungcheong = dataset_chungcheong.reset_index()
del dataset_chungcheong['index']

In [26]:
del dataset_chungcheong['일자']
del dataset_chungcheong['입출구']

In [27]:
dataset_chungcheong = pd.concat([imsi_day, dataset_chungcheong], axis = 1)

In [28]:
day_time = []

for i in range(len(dataset_chungcheong)):
    for j in range(1,25):
        day_time.append(dataset_chungcheong.iloc[i][0] +'.' + dataset_chungcheong.columns[j])

In [29]:
car_time = []

for i in range(len(dataset_chungcheong)):
    for j in range(1,25):
        car_time.append(dataset_chungcheong.iloc[i][j])

In [30]:
dataset_chungcheong = pd.DataFrame({'시간' : day_time, '충청 교통량' : car_time })

In [31]:
dataset_chungcheong = dataset_chungcheong.set_index('시간')

In [32]:
dataset_chungcheong

                충청 교통량
시간
2010.01.01.00시   9,168
2010.01.01.01시   8,243
2010.01.01.02시   6,313
2010.01.01.03시   5,346
2010.01.01.04시   4,963
2010.01.01.05시   5,603
2010.01.01.06시   6,985
2010.01.01.07시   9,384
2010.01.01.08시  14,315
2010.01.01.09시  20,783
2010.01.01.10시  30,825
2010.01.01.11시  37,554
2010.01.01.12시  36,775
2010.01.01.13시  36,152
2010.01.01.14시  38,707
2010.01.01.15시  39,786
2010.01.01.16시  38,613
2010.01.01.17시  36,238
2010.01.01.18시  30,689
2010.01.01.19시  23,359
2010.01.01.20시  19,413
2010.01.01.21시  16,148
2010.01.01.22시  11,829
2010.01.01.23시   7,870
2010.01.02.00시   5,247
2010.01.02.01시   3,426
2010.01.02.02시   2,300
2010.01.02.03시   1,956
2010.01.02.04시   2,388
2010.01.02.05시   3,657
...                ...
2010.12.30.18시  32,997
2010.12.30.19시  23,161
2010.12.30.20시  16,795
2010.12.30.21시  13,553
2010.12.30.22시  10,651
2010.12.30.23시   7,597
2010.12.31.00시   5,731
2010.12.31.01시   4,090
2010.12.31.02시   3,225
2010.12.31.03시   2,996
2010.12.31.04시   3,436
2010.12.31.05시   4,583
2010.12.31.06시   8,925
2010.12.31.07시  23,290
2010.12.31.08시  30,792
2010.12.31.09시  25,302
2010.12.31.10시  28,039
2010.12.31.11시  29,980
2010.12.31.12시  30,420
2010.12.31.13시  34,923
2010.12.31.14시  38,772
2010.12.31.15시  41,275
2010.12.31.16시  43,889
2010.12.31.17시  46,084
2010.12.31.18시  46,100
2010.12.31.19시  36,815
2010.12.31.20시  28,978
2010.12.31.21시  23,266
2010.12.31.22시  17,823
2010.12.31.23시  12,174

[8760 rows x 1 columns]

# 경남권역

In [33]:
dataset_gyeongnam = pd.read_excel('car_gyeongnam_2010.xlsx')

In [34]:
dataset_gyeongnam

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"8,491","8,001","6,319","5,065","5,549","6,987","8,562","10,140",...,"44,129","36,907","36,279","32,856","26,561","21,385","18,274","15,774","11,128","7,331"
1,NaN,출구,"10,189","8,901","7,280","5,666","5,518","6,914","8,194","8,529",...,"37,227","38,106","38,721","37,239","31,889","25,703","21,059","18,114","13,526","8,963"
2,NaN,합계,"18,680","16,902","13,599","10,731","11,067","13,901","16,756","18,669",...,"81,356","75,013","75,000","70,095","58,450","47,088","39,333","33,888","24,654","16,294"
3,2010.01.02,입구,"5,089","3,158","2,433","2,193","2,602","4,551","8,926","13,912",...,"38,195","38,755","39,180","38,181","30,904","23,524","20,457","17,566","12,423","9,042"
4,NaN,출구,"6,169","3,880","2,788","2,231","2,241","3,353","6,903","12,071",...,"36,103","37,290","38,784","39,842","35,899","27,874","23,945","20,258","15,563","10,365"
5,NaN,합계,"11,258","7,038","5,221","4,424","4,843","7,904","15,829","25,983",...,"74,298","76,045","77,964","78,023","66,803","51,398","44,402","37,824","27,986","19,407"
6,2010.01.03,입구,"6,214","3,903","3,035","2,318","2,252","3,750","7,103","10,773",...,"34,360","35,221","33,422","31,443","25,054","20,764","20,258","16,850","11,496","7,535"
7,NaN,출구,"7,225","4,587","3,414","2,498","2,043","2,767","5,613","8,973",...,"32,976","34,722","35,648","34,628","29,688","24,263","22,269","18,889","13,980","9,268"
8,NaN,합계,"13,439","8,490","6,449","4,816","4,295","6,517","12,716","19,746",...,"67,336","69,943","69,070","66,071","54,742","45,027","42,527","35,739","25,476","16,803"
9,2010.01.04,입구,"4,678","2,828","2,037","2,149","3,932","9,268","21,689","35,944",...,"27,384","26,110","25,659","27,932","26,829","18,899","15,204","11,671","8,418","5,795"
10,NaN,출구,"5,896","3,486","2,313","1,920","2,896","6,254","16,806","35,101",...,"27,661","27,308","26,915","28,530","29,071","21,153","16,525","12,885","9,522","6,536"
11,NaN,합계,"10,574","6,314","4,350","4,069","6,828","15,522","38,495","71,045",...,"55,045","53,418","52,574","56,462","55,900","40,052","31,729","24,556","17,940","12,331"
12,2010.01.05,입구,"4,058","2,728","2,047","2,025","2,869","5,622","14,722","31,303",...,"29,313","28,232","27,935","30,658","28,991","20,467","16,829","13,281","9,601","6,590"
13,NaN,출구,"4,541","3,173","2,328","1,997","2,398","4,215","11,603","28,820",...,"30,233","29,906","29,366","31,321","31,854","22,705","17,891","14,188","10,658","7,112"
14,NaN,합계,"8,599","5,901","4,375","4,022","5,267","9,837","26,325","60,123",...,"59,546","58,138","57,301","61,979","60,845","43,172","34,720","27,469","20,259","13,702"
15,2010.01.06,입구,"4,564","3,110","2,300","2,169","3,009","5,677","15,040","31,856",...,"30,597","29,577","29,598","32,793","30,971","20,686","16,278","13,552","9,685","6,974"
16,NaN,출구,"5,128","3,613","2,530","2,148","2,494","4,391","11,996","30,037",...,"30,304","30,406","30,351","32,308","33,485","23,702","17,521","14,273","10,643","7,693"
17,NaN,합계,"9,692","6,723","4,830","4,317","5,503","10,068","27,036","61,893",...,"60,901","59,983","59,949","65,101","64,456","44,388","33,799","27,825","20,328","14,667"
18,2010.01.07,입구,"4,728","3,148","2,367","2,274","3,032","5,698","14,974","31,976",...,"30,046","29,975","29,973","32,518","30,485","21,348","17,543","13,843","9,530","7,007"
19,NaN,출구,"5,329","3,767","2,644","2,249","2,486","4,465","11,947","30,036",...,"29,731","30,358","30,651","32,112","32,541","23,914","18,673","14,976","10,755","7,768"
20,NaN,합계,"10,057","6,915","5,011","4,523","5,518","10,163","26,921","62,012",...,"59,777","60,333","60,624","64,630","63,026","45,262","36,216","28,819","20,285","14,775"
21,2010.01.08,입구,"4,924","3,200","2,580","2,369","3,192","5,893","15,063","31,596",...,"31,784","31,081","32,117","35,818","35,760","26,278","21,212","16,648","12,076","8,215"
22,NaN,출구,"5,386","3,793","2,812","2,264","2,579","4,643","12,368","29,885",...,"31,413","31,788","32,261","35,276","36,642","30,416","24,222","18,879","14,213","9,693"
23,NaN,합계,"10,310","6,993","5,392","4,633","5,771","10,536","27,431","61,481",...,"63,197","62,869","64,378","71,094","72,402","56,694","45,434","35,527","26,289","17,908"
24,2010.01.09,입구,"6,161","4,197","3,452","3,038","3,536","6,001","13,077","23,910",...,"33,803","34,901","36,613","38,500","31,137","22,158","17,494","15,722","12,059","9,066"
25,NaN,출구,"7,056","4,879","3,772","3,082","3,091","4,769","10,719","22,009",...,"33,252","34,577","36,266","38,474","35,286","26,922","19,966","17,302","13,784","10,425"
26,NaN,합계,"13,217","9,076","7,224","6,120","6,627","10,770","23,796","45,919",...,"67,055","69,478","72,879","76,974","66,423","49,080","37,460","33,024","25,843","19,491"
27,2010.01.10,입구,"6,537","4,302","3,407","2,601","2,508","4,071","7,907","11,583",...,"31,111","33,025","33,893","32,399","26,221","20,006","19,430","16,026","11,217","7,594"
28,NaN,출구,"7,488","5,066","3,776","2,837","2,281","3,087","6,384","9,921",...,"29,845","32,157","33,827","34,509","29,411","22,555","20,780","17,738","13,357","8,996"
29,NaN,합계,"14,025","9,368","7,183","5,438","4,789","7,158","14,291","21,504",...,"60,956","65,182","67,720","66,908","55,632","42,561","40,210","33,764","24,574","16,590"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"5,687","3,699","2,749","2,653","3,445","6,865","17,903","35,706",...,"32,982","32,277","32,295","37,312","33,896","23,556","18,350","15,669","11,788","8,645"
1066,NaN,출구,"6,575","4,371","3,163","2,717","3,055","5,553","14,642","33,803",...,"32,620","32,742","32,604","36,318","36,101","26,765","19,794","16,448","12,961","9,475"
1067,NaN,합계,"12,262","8,070","5,912","5,370","6,500","12,418","32,545","69,509",...,"65,602","65,019","64,899","73,630","69,997","50,321","38,144","32,117","24,749","18,120"
1068,2010.12.23,입구,"6,109","4,022","2,931","2,608","3,527","7,152","17,726","35,365",...,"32,917","32,857","33,777","36,248","32,348","23,079","19,421","16,027","11,916","8,962"
1069,NaN,출구,"6,835","4,512","3,284","2,630","2,912","5,487","14,783","33,123",...,"32,251","32,848","33,427","35,453","34,533","26,008","20,917","17,137","13,003","9,786"
1070,NaN,합계,"12,944","8,534","6,215","5,238","6,439","12,639","32,509","68,488",...,"65,168","65,705","67,204","71,701","66,881","49,087","40,338","33,164","24,919","18,748"
1071,2010.12.24,입구,"6,286","4,136","2,968","2,745","3,423","6,702","16,816","34,495",...,"33,160","32,903","34,700","39,733","39,850","31,914","25,327","20,800","14,959","10,671"
1072,NaN,출구,"7,042","4,787","3,388","2,777","2,916","5,363","13,887","32,558",...,"32,835","33,637","34,280","38,258","39,342","35,043","29,317","24,364","19,927","13,272"
1073,NaN,합계,"13,328","8,923","6,356","5,522","6,339","12,065","30,703","67,053",...,"65,995","66,540","68,980","77,991","79,192","66,957","54,644","45,164","34,886","23,943"
1074,2010.12.25,입구,"7,694","5,325","3,956","3,295","3,400","5,558","11,168","17,577",...,"34,052","33,956","34,270","34,839","28,074","21,478","18,376","16,894","13,863","10,754"
1075,NaN,출구,"9,451","6,552","4,732","3,652","3,237","4,682","9,365","16,654",...,"34,317","35,193","36,167","36,090","32,099","24,429","19,724","17,553","14,519","11,307"
1076,NaN,합계,"17,145","11,877","8,688","6,947","6,637","10,240","20,533","34,231",...,"68,369","69,149","70,437","70,929","60,173","45,907","38,100","34,447","28,382","22,061"
1077,2010.12.26,입구,"7,284","4,728","3,339","2,312","2,495","3,921","7,462","11,182",...,"34,094","35,987","35,434","32,820","26,577","22,881","21,192","17,368","11,567","7,940"
1078,NaN,출구,"8,084","5,176","3,677","2,469","2,154","3,036","6,302","10,108",...,"31,624","34,001","35,844","34,219","28,821","23,161","21,434","19,553","14,436","9,430"
1079,NaN,합계,"15,368","9,904","7,016","4,781","4,649","6,957","13,764","21,290",...,"65,718","69,988","71,278","67,039","55,398","46,042","42,626","36,921","26,003","17,370"
1080,2010.12.27,입구,"4,508","2,711","2,013","2,209","3,675","9,115","22,100","38,598",...,"32,406","31,659","31,917","33,892","31,270","22,627","18,719","14,860","10,664","7,763"
1081,NaN,출구,"5,564","3,296","2,301","2,001","2,588","5,931","16,218","34,695",...,"32,113","32,145","32,419","34,117","33,261","25,037","19,753","15,475","11,793","8,424"
1082,NaN,합계,"10,072","6,007","4,314","4,210","6,263","15,046","38,318","73,293",...,"64,519","63,804","64,336","68,009","64,531","47,664","38,472","30,335","22,457","16,187"
1083,2010.12.28,입구,"5,336","3,604","2,708","2,473","3,362","6,670","17,062","34,382",...,"31,861","31,502","31,690","33,919","31,013","21,761","18,100","14,543","10,698","7,882"
1084,NaN,출구,"6,113","4,173","3,039","2,519","2,848","5,166","13,752","31,853",...,"31,533","32,181","32,550","33,566","32,881","25,069","19,653","15,194","11,982","9,078"
1085,NaN,합계,"11,449","7,777","5,747","4,992","6,210","11,836","30,814","66,235",...,"63,394","63,683","64,240","67,485","63,894","46,830","37,753","29,737","22,680","16,960"
1086,2010.12.29,입구,"5,541","3,597","2,753","2,404","3,246","6,151","16,108","33,994",...,"32,742","32,240","32,395","36,117","32,937","22,652","19,243","15,171","11,910","8,492"
1087,NaN,출구,"6,460","4,334","3,087","2,423","2,750","4,864","13,216","31,381",...,"32,712","33,148","34,054","36,314","35,384","26,267","20,386","16,541","13,028","9,698"
1088,NaN,합계,"12,001","7,931","5,840","4,827","5,996","11,015","29,324","65,375",...,"65,454","65,388","66,449","72,431","68,321","48,919","39,629","31,712","24,938","18,190"
1089,2010.12.30,입구,"6,384","4,097","2,971","2,514","3,118","6,093","16,189","32,874",...,"31,768","31,080","31,333","33,266","30,920","21,736","17,978","14,747","11,294","8,659"
1090,NaN,출구,"7,399","4,983","3,494","2,772","2,795","4,967","13,096","31,156",...,"31,786","31,977","31,803","32,395","32,918","26,540","19,526","15,854","12,524","9,505"
1091,NaN,합계,"13,783","9,080","6,465","5,286","5,913","11,060","29,285","64,030",...,"63,554","63,057","63,136","65,661","63,838","48,276","37,504","30,601","23,818","18,164"
1092,2010.12.31,입구,"6,331","4,295","3,113","2,574","3,013","5,392","13,459","30,429",...,"34,350","34,757","36,615","40,210","36,375","29,850","23,924","20,865","16,087","10,245"
1093,NaN,출구,"7,033","5,021","3,535","2,705","2,734","4,558","10,989","28,454",...,"33,510","34,351","36,906","38,843","37,545","33,646","27,973","24,975","20,860","14,269"
1094,NaN,합계,"13,364","9,316","6,648","5,279","5,747","9,950","24,448","58,883",...,"67,860","69,108","73,521","79,053","73,920","63,496","51,897","45,840","36,947","24,514"

In [35]:
imsi_day = pd.DataFrame(dataset_gyeongnam['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_gyeongnam = dataset_gyeongnam[(dataset_gyeongnam.입출구 == '합계')]
dataset_gyeongnam = dataset_gyeongnam.reset_index()
del dataset_gyeongnam['index']

In [36]:
del dataset_gyeongnam['일자']
del dataset_gyeongnam['입출구']

In [37]:
dataset_gyeongnam = pd.concat([imsi_day, dataset_gyeongnam], axis = 1)

In [38]:
day_time = []

for i in range(len(dataset_gyeongnam)):
    for j in range(1,25):
        day_time.append(dataset_gyeongnam.iloc[i][0] +'.' + dataset_gyeongnam.columns[j])

In [39]:
car_time = []

for i in range(len(dataset_gyeongnam)):
    for j in range(1,25):
        car_time.append(dataset_gyeongnam.iloc[i][j])

In [40]:
dataset_gyeongnam = pd.DataFrame({'시간' : day_time, '경남 교통량' : car_time })

In [41]:
dataset_gyeongnam = dataset_gyeongnam.set_index('시간')

In [42]:
dataset_gyeongnam

                경남 교통량
시간
2010.01.01.00시  18,680
2010.01.01.01시  16,902
2010.01.01.02시  13,599
2010.01.01.03시  10,731
2010.01.01.04시  11,067
2010.01.01.05시  13,901
2010.01.01.06시  16,756
2010.01.01.07시  18,669
2010.01.01.08시  28,909
2010.01.01.09시  42,148
2010.01.01.10시  59,758
2010.01.01.11시  72,002
2010.01.01.12시  73,095
2010.01.01.13시  71,840
2010.01.01.14시  81,356
2010.01.01.15시  75,013
2010.01.01.16시  75,000
2010.01.01.17시  70,095
2010.01.01.18시  58,450
2010.01.01.19시  47,088
2010.01.01.20시  39,333
2010.01.01.21시  33,888
2010.01.01.22시  24,654
2010.01.01.23시  16,294
2010.01.02.00시  11,258
2010.01.02.01시   7,038
2010.01.02.02시   5,221
2010.01.02.03시   4,424
2010.01.02.04시   4,843
2010.01.02.05시   7,904
...                ...
2010.12.30.18시  63,838
2010.12.30.19시  48,276
2010.12.30.20시  37,504
2010.12.30.21시  30,601
2010.12.30.22시  23,818
2010.12.30.23시  18,164
2010.12.31.00시  13,364
2010.12.31.01시   9,316
2010.12.31.02시   6,648
2010.12.31.03시   5,279
2010.12.31.04시   5,747
2010.12.31.05시   9,950
2010.12.31.06시  24,448
2010.12.31.07시  58,883
2010.12.31.08시  61,495
2010.12.31.09시  54,315
2010.12.31.10시  59,037
2010.12.31.11시  60,471
2010.12.31.12시  57,906
2010.12.31.13시  61,629
2010.12.31.14시  67,860
2010.12.31.15시  69,108
2010.12.31.16시  73,521
2010.12.31.17시  79,053
2010.12.31.18시  73,920
2010.12.31.19시  63,496
2010.12.31.20시  51,897
2010.12.31.21시  45,840
2010.12.31.22시  36,947
2010.12.31.23시  24,514

[8760 rows x 1 columns]

# 경북권역

In [43]:
import pandas as pd
import numpy as np

In [44]:
dataset_gyeongbuk = pd.read_excel('car_gyeongbuk_2010.xlsx')

In [45]:
dataset_gyeongbuk

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"4,733","5,280","3,705","3,172","3,532","3,783","3,758","5,270",...,"23,934","24,155","24,070","22,005","17,995","14,428","11,595","9,143","6,378","4,048"
1,NaN,출구,"8,042","6,878","5,876","4,808","4,562","5,387","5,034","4,604",...,"24,675","25,676","25,161","24,524","20,687","16,325","13,552","10,697","8,022","5,298"
2,NaN,합계,"12,775","12,158","9,581","7,980","8,094","9,170","8,792","9,874",...,"48,609","49,831","49,231","46,529","38,682","30,753","25,147","19,840","14,400","9,346"
3,2010.01.02,입구,"2,604","1,727","1,205","1,097","1,477","2,642","4,546","7,546",...,"25,992","27,263","27,402","25,210","20,338","15,568","12,194","9,416","6,260","4,334"
4,NaN,출구,"3,435","2,168","1,454","1,066","1,134","1,603","3,312","5,888",...,"23,143","24,324","25,243","24,996","22,496","17,721","14,026","11,256","8,074","5,476"
5,NaN,합계,"6,039","3,895","2,659","2,163","2,611","4,245","7,858","13,434",...,"49,135","51,587","52,645","50,206","42,834","33,289","26,220","20,672","14,334","9,810"
6,2010.01.03,입구,"2,743","1,936","1,337","1,104","1,300","2,070","3,549","5,724",...,"25,246","25,884","24,892","21,736","17,496","13,895","12,457","9,421","6,120","3,891"
7,NaN,출구,"3,593","2,459","1,688","1,279","1,068","1,321","2,551","4,086",...,"19,964","21,852","23,086","23,092","20,564","15,829","13,439","10,936","7,845","5,124"
8,NaN,합계,"6,336","4,395","3,025","2,383","2,368","3,391","6,100","9,810",...,"45,210","47,736","47,978","44,828","38,060","29,724","25,896","20,357","13,965","9,015"
9,2010.01.04,입구,"2,358","1,573","1,233","1,381","2,301","4,751","10,166","19,590",...,"11,348","11,286","11,334","11,951","11,277","7,528","5,309","3,784","2,694","1,986"
10,NaN,출구,"3,199","1,934","1,269","1,002","1,158","2,358","6,331","16,417",...,"13,300","11,993","11,466","12,183","12,261","9,753","6,332","4,606","3,213","2,303"
11,NaN,합계,"5,557","3,507","2,502","2,383","3,459","7,109","16,497","36,007",...,"24,648","23,279","22,800","24,134","23,538","17,281","11,641","8,390","5,907","4,289"
12,2010.01.05,입구,"1,329","1,079",838,976,"1,214","1,979","5,086","13,090",...,"15,621","15,523","15,267","15,514","15,557","10,384","7,487","6,222","4,331","3,114"
13,NaN,출구,"1,624","1,150",892,810,917,"1,358","3,069","9,673",...,"15,749","15,697","15,536","15,960","16,267","12,591","8,426","6,897","5,010","3,533"
14,NaN,합계,"2,953","2,229","1,730","1,786","2,131","3,337","8,155","22,763",...,"31,370","31,220","30,803","31,474","31,824","22,975","15,913","13,119","9,341","6,647"
15,2010.01.06,입구,"2,249","1,532","1,302","1,375","1,801","2,883","6,469","15,621",...,"17,109","16,942","16,934","17,732","17,508","11,682","8,511","6,874","5,067","3,370"
16,NaN,출구,"2,514","1,702","1,211","1,089","1,180","1,818","4,135","11,843",...,"17,224","17,239","17,057","17,988","18,373","14,438","9,488","7,762","5,790","4,052"
17,NaN,합계,"4,763","3,234","2,513","2,464","2,981","4,701","10,604","27,464",...,"34,333","34,181","33,991","35,720","35,881","26,120","17,999","14,636","10,857","7,422"
18,2010.01.07,입구,"2,386","1,773","1,372","1,375","1,865","3,100","6,771","16,109",...,"17,361","17,141","17,337","17,780","17,268","11,771","8,656","7,135","5,243","3,504"
19,NaN,출구,"2,826","1,960","1,371","1,126","1,210","1,893","4,412","12,281",...,"17,175","17,215","17,251","17,800","18,615","13,982","9,860","8,014","6,024","4,204"
20,NaN,합계,"5,212","3,733","2,743","2,501","3,075","4,993","11,183","28,390",...,"34,536","34,356","34,588","35,580","35,883","25,753","18,516","15,149","11,267","7,708"
21,2010.01.08,입구,"2,547","1,794","1,323","1,508","1,920","3,179","6,794","15,722",...,"17,786","18,812","19,268","20,326","21,526","15,240","11,007","8,537","5,948","4,302"
22,NaN,출구,"3,107","2,099","1,408","1,160","1,264","1,892","4,413","11,896",...,"17,939","18,488","19,023","19,853","21,649","18,018","13,563","10,937","8,000","5,697"
23,NaN,합계,"5,654","3,893","2,731","2,668","3,184","5,071","11,207","27,618",...,"35,725","37,300","38,291","40,179","43,175","33,258","24,570","19,474","13,948","9,999"
24,2010.01.09,입구,"3,056","2,197","1,627","1,595","1,908","3,269","6,291","11,429",...,"20,811","21,928","22,423","22,860","19,446","13,868","10,580","8,575","6,341","4,492"
25,NaN,출구,"4,006","2,703","1,839","1,477","1,484","2,125","4,297","8,959",...,"19,907","21,605","22,499","24,374","22,449","16,815","12,705","10,039","8,115","5,766"
26,NaN,합계,"7,062","4,900","3,466","3,072","3,392","5,394","10,588","20,388",...,"40,718","43,533","44,922","47,234","41,895","30,683","23,285","18,614","14,456","10,258"
27,2010.01.10,입구,"3,206","2,156","1,552","1,207","1,341","2,336","4,027","6,538",...,"20,786","21,956","22,086","20,840","16,843","13,087","11,293","8,901","5,922","3,902"
28,NaN,출구,"3,999","2,710","1,938","1,355","1,160","1,550","2,939","4,916",...,"17,029","18,739","20,565","21,163","18,965","15,072","12,755","10,402","7,537","5,104"
29,NaN,합계,"7,205","4,866","3,490","2,562","2,501","3,886","6,966","11,454",...,"37,815","40,695","42,651","42,003","35,808","28,159","24,048","19,303","13,459","9,006"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"2,888","2,014","1,574","1,696","2,168","4,091","9,448","19,260",...,"19,370","19,419","19,840","21,862","20,015","12,816","9,711","8,303","5,996","4,363"
1066,NaN,출구,"3,483","2,432","1,670","1,397","1,440","2,453","6,253","15,408",...,"18,958","19,209","19,382","20,542","21,870","16,617","11,360","9,201","7,082","5,037"
1067,NaN,합계,"6,371","4,446","3,244","3,093","3,608","6,544","15,701","34,668",...,"38,328","38,628","39,222","42,404","41,885","29,433","21,071","17,504","13,078","9,400"
1068,2010.12.23,입구,"3,019","2,100","1,690","1,634","2,317","3,994","9,265","19,213",...,"19,376","19,130","19,937","21,484","19,314","12,587","9,850","29,936","5,945","4,355"
1069,NaN,출구,"3,650","2,440","1,744","1,376","1,448","2,415","6,004","15,403",...,"18,987","18,911","19,326","21,186","21,311","15,171","11,287","9,354","7,223","5,306"
1070,NaN,합계,"6,669","4,540","3,434","3,010","3,765","6,409","15,269","34,616",...,"38,363","38,041","39,263","42,670","40,625","27,758","21,137","39,290","13,168","9,661"
1071,2010.12.24,입구,"3,069","2,033","1,599","1,659","2,282","3,747","8,474","18,235",...,"20,107","20,546","21,853","25,050","26,777","20,104","14,649","10,509","7,341","5,350"
1072,NaN,출구,"3,732","2,536","1,744","1,371","1,479","2,302","5,314","14,391",...,"19,228","19,955","20,588","23,068","24,238","22,848","19,559","15,398","11,209","7,791"
1073,NaN,합계,"6,801","4,569","3,343","3,030","3,761","6,049","13,788","32,626",...,"39,335","40,501","42,441","48,118","51,015","42,952","34,208","25,907","18,550","13,141"
1074,2010.12.25,입구,"3,605","2,491","1,956","1,668","1,865","2,906","5,460","9,278",...,"20,823","20,892","20,939","20,650","16,898","12,376","10,010","7,931","6,434","4,546"
1075,NaN,출구,"5,501","3,735","2,592","1,822","1,624","2,095","3,820","7,346",...,"20,623","21,349","21,454","22,165","20,188","15,257","11,741","9,906","7,830","6,114"
1076,NaN,합계,"9,106","6,226","4,548","3,490","3,489","5,001","9,280","16,624",...,"41,446","42,241","42,393","42,815","37,086","27,633","21,751","17,837","14,264","10,660"
1077,2010.12.26,입구,"3,000","1,971","1,381","1,064","1,195","2,066","3,698","5,843",...,"21,892","22,958","22,801","20,471","16,273","12,887","10,245","8,459","6,169","3,627"
1078,NaN,출구,"4,206","2,727","1,860","1,228","1,045","1,402","2,595","4,264",...,"17,481","19,492","21,139","21,226","17,659","14,962","14,326","11,088","8,400","5,412"
1079,NaN,합계,"7,206","4,698","3,241","2,292","2,240","3,468","6,293","10,107",...,"39,373","42,450","43,940","41,697","33,932","27,849","24,571","19,547","14,569","9,039"
1080,2010.12.27,입구,"2,110","1,338","1,111","1,154","1,900","3,687","8,678","17,137",...,"18,023","17,672","17,049","17,838","16,345","10,958","8,562","7,286","5,162","3,775"
1081,NaN,출구,"3,054","1,814","1,140",967,"1,079","1,800","4,786","14,291",...,"17,652","17,747","17,698","17,890","18,179","13,466","9,930","8,300","6,221","4,386"
1082,NaN,합계,"5,164","3,152","2,251","2,121","2,979","5,487","13,464","31,428",...,"35,675","35,419","34,747","35,728","34,524","24,424","18,492","15,586","11,383","8,161"
1083,2010.12.28,입구,"2,626","1,849","1,323","1,546","1,990","3,590","8,173","17,568",...,"14,475","14,529","15,071","15,010","13,467","9,193","6,641","5,187","3,935","2,761"
1084,NaN,출구,"3,177","2,204","1,484","1,284","1,383","2,091","4,884","13,269",...,"13,939","14,339","13,756","14,721","16,673","11,747","7,816","6,619","5,098","3,881"
1085,NaN,합계,"5,803","4,053","2,807","2,830","3,373","5,681","13,057","30,837",...,"28,414","28,868","28,827","29,731","30,140","20,940","14,457","11,806","9,033","6,642"
1086,2010.12.29,입구,"2,119","1,518","1,156","1,239","1,561","2,840","6,916","15,313",...,"19,810","19,860","20,323","20,866","18,843","12,757","9,260","7,482","5,691","3,919"
1087,NaN,출구,"2,582","1,816","1,184","1,080","1,134","1,720","4,044","11,402",...,"18,692","19,293","20,243","20,750","20,448","16,403","10,990","8,816","6,835","4,919"
1088,NaN,합계,"4,701","3,334","2,340","2,319","2,695","4,560","10,960","26,715",...,"38,502","39,153","40,566","41,616","39,291","29,160","20,250","16,298","12,526","8,838"
1089,2010.12.30,입구,"2,771","1,873","1,425","1,386","1,677","2,887","6,893","16,426",...,"18,462","18,472","18,583","19,375","17,498","11,366","8,552","6,675","5,223","3,720"
1090,NaN,출구,"3,500","2,435","1,562","1,260","1,321","1,852","4,215","12,210",...,"17,837","18,367","18,377","19,376","19,893","14,670","10,147","8,171","6,369","4,571"
1091,NaN,합계,"6,271","4,308","2,987","2,646","2,998","4,739","11,108","28,636",...,"36,299","36,839","36,960","38,751","37,391","26,036","18,699","14,846","11,592","8,291"
1092,2010.12.31,입구,"2,687","1,909","1,470","1,368","1,658","2,831","6,328","15,327",...,"21,324","22,106","23,748","24,953","23,404","19,318","14,602","10,576","8,105","5,462"
1093,NaN,출구,"3,342","2,261","1,645","1,292","1,273","1,851","4,081","11,595",...,"20,436","22,202","23,200","25,462","24,849","22,877","19,502","16,299","13,342","9,861"
1094,NaN,합계,"6,029","4,170","3,115","2,660","2,931","4,682","10,409","26,922",...,"41,760","44,308","46,948","50,415","48,253","42,195","34,104","26,875","21,447","15,323"

In [46]:
imsi_day = pd.DataFrame(dataset_gyeongbuk['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_gyeongbuk = dataset_gyeongbuk[(dataset_gyeongbuk.입출구 == '합계')]
dataset_gyeongbuk = dataset_gyeongbuk.reset_index()
del dataset_gyeongbuk['index']

In [47]:
del dataset_gyeongbuk['일자']
del dataset_gyeongbuk['입출구']

In [48]:
dataset_gyeongbuk = pd.concat([imsi_day, dataset_gyeongbuk], axis = 1)

In [49]:
day_time = []

for i in range(len(dataset_gyeongbuk)):
    for j in range(1,25):
        day_time.append(dataset_gyeongbuk.iloc[i][0] +'.' + dataset_gyeongbuk.columns[j])

In [50]:
car_time = []

for i in range(len(dataset_gyeongbuk)):
    for j in range(1,25):
        car_time.append(dataset_gyeongbuk.iloc[i][j])

In [51]:
dataset_gyeongbuk = pd.DataFrame({'시간' : day_time, '경북 교통량' : car_time })

In [52]:
dataset_gyeongbuk = dataset_gyeongbuk.set_index('시간')

In [53]:
dataset_gyeongbuk

                경북 교통량
시간
2010.01.01.00시  12,775
2010.01.01.01시  12,158
2010.01.01.02시   9,581
2010.01.01.03시   7,980
2010.01.01.04시   8,094
2010.01.01.05시   9,170
2010.01.01.06시   8,792
2010.01.01.07시   9,874
2010.01.01.08시  16,498
2010.01.01.09시  25,855
2010.01.01.10시  38,301
2010.01.01.11시  47,604
2010.01.01.12시  47,534
2010.01.01.13시  46,760
2010.01.01.14시  48,609
2010.01.01.15시  49,831
2010.01.01.16시  49,231
2010.01.01.17시  46,529
2010.01.01.18시  38,682
2010.01.01.19시  30,753
2010.01.01.20시  25,147
2010.01.01.21시  19,840
2010.01.01.22시  14,400
2010.01.01.23시   9,346
2010.01.02.00시   6,039
2010.01.02.01시   3,895
2010.01.02.02시   2,659
2010.01.02.03시   2,163
2010.01.02.04시   2,611
2010.01.02.05시   4,245
...                ...
2010.12.30.18시  37,391
2010.12.30.19시  26,036
2010.12.30.20시  18,699
2010.12.30.21시  14,846
2010.12.30.22시  11,592
2010.12.30.23시   8,291
2010.12.31.00시   6,029
2010.12.31.01시   4,170
2010.12.31.02시   3,115
2010.12.31.03시   2,660
2010.12.31.04시   2,931
2010.12.31.05시   4,682
2010.12.31.06시  10,409
2010.12.31.07시  26,922
2010.12.31.08시  31,839
2010.12.31.09시  28,500
2010.12.31.10시  32,822
2010.12.31.11시  34,532
2010.12.31.12시  33,274
2010.12.31.13시  37,088
2010.12.31.14시  41,760
2010.12.31.15시  44,308
2010.12.31.16시  46,948
2010.12.31.17시  50,415
2010.12.31.18시  48,253
2010.12.31.19시  42,195
2010.12.31.20시  34,104
2010.12.31.21시  26,875
2010.12.31.22시  21,447
2010.12.31.23시  15,323

[8760 rows x 1 columns]

# 전남권역

In [54]:
dataset_jeonnam = pd.read_excel('car_jeonnam_2010.xlsx')

In [55]:
dataset_jeonnam

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"1,256","1,122",943,902,964,"1,219","1,561","1,973",...,"10,609","10,798","10,172","8,739","6,800","4,896","3,941","3,043","2,091","1,323"
1,NaN,출구,"2,294","1,920","1,594","1,324","1,348","1,358","1,699","1,854",...,"11,267","11,857","11,976","11,708","9,525","7,053","5,332","4,099","2,949","1,880"
2,NaN,합계,"3,550","3,042","2,537","2,226","2,312","2,577","3,260","3,827",...,"21,876","22,655","22,148","20,447","16,325","11,949","9,273","7,142","5,040","3,203"
3,2010.01.02,입구,887,546,435,467,558,"1,029","1,873","3,167",...,"12,735","13,527","12,842","11,158","8,298","6,136","4,800","3,679","2,302","1,733"
4,NaN,출구,"1,243",880,636,516,508,705,"1,386","2,483",...,"10,941","11,727","12,338","11,807","9,691","7,020","5,141","4,148","3,030","2,062"
5,NaN,합계,"2,130","1,426","1,071",983,"1,066","1,734","3,259","5,650",...,"23,676","25,254","25,180","22,965","17,989","13,156","9,941","7,827","5,332","3,795"
6,2010.01.03,입구,"1,074",714,536,506,520,905,"1,717","2,658",...,"11,907","11,890","10,870","9,669","7,578","5,856","5,190","3,979","2,691","1,734"
7,NaN,출구,"1,431","1,053",728,562,446,581,"1,134","1,793",...,"9,430","10,523","11,204","10,961","9,297","6,827","5,765","4,503","3,264","2,261"
8,NaN,합계,"2,505","1,767","1,264","1,068",966,"1,486","2,851","4,451",...,"21,337","22,413","22,074","20,630","16,875","12,683","10,955","8,482","5,955","3,995"
9,2010.01.04,입구,"1,000",568,511,609,"1,052","2,157","4,470","7,698",...,"6,386","6,228","6,327","6,205","5,952","3,466","2,515","2,014","1,468","1,016"
10,NaN,출구,"1,389",868,604,484,580,"1,155","2,842","6,517",...,"6,170","6,419","6,399","6,667","6,882","4,607","3,018","2,409","1,772","1,372"
11,NaN,합계,"2,389","1,436","1,115","1,093","1,632","3,312","7,312","14,215",...,"12,556","12,647","12,726","12,872","12,834","8,073","5,533","4,423","3,240","2,388"
12,2010.01.05,입구,687,464,347,378,477,786,"1,502","4,077",...,"5,558","5,375","5,212","5,183","4,928","2,975","2,073","1,609","1,174",892
13,NaN,출구,876,695,467,437,394,634,"1,190","2,967",...,"5,412","5,701","5,489","5,379","6,059","3,883","2,534","2,001","1,510","1,082"
14,NaN,합계,"1,563","1,159",814,815,871,"1,420","2,692","7,044",...,"10,970","11,076","10,701","10,562","10,987","6,858","4,607","3,610","2,684","1,974"
15,2010.01.06,입구,591,457,383,428,580,830,"1,607","4,359",...,"6,536","6,471","6,234","6,568","6,366","3,779","2,678","2,010","1,480","1,014"
16,NaN,출구,799,573,536,450,504,719,"1,398","3,349",...,"6,477","6,837","6,551","6,815","6,931","4,840","3,313","2,426","1,857","1,371"
17,NaN,합계,"1,390","1,030",919,878,"1,084","1,549","3,005","7,708",...,"13,013","13,308","12,785","13,383","13,297","8,619","5,991","4,436","3,337","2,385"
18,2010.01.07,입구,817,480,441,481,684,"1,039","2,135","5,499",...,"7,172","7,049","6,992","7,255","6,803","4,030","3,071","2,450","1,805","1,318"
19,NaN,출구,958,727,523,459,527,800,"1,641","4,312",...,"6,971","7,324","7,260","7,515","8,044","5,294","3,540","2,872","2,339","1,655"
20,NaN,합계,"1,775","1,207",964,940,"1,211","1,839","3,776","9,811",...,"14,143","14,373","14,252","14,770","14,847","9,324","6,611","5,322","4,144","2,973"
21,2010.01.08,입구,930,618,520,515,720,"1,202","2,467","5,636",...,"8,245","8,295","8,532","9,114","10,327","6,597","4,356","3,318","2,381","1,660"
22,NaN,출구,"1,151",788,623,528,569,872,"1,890","4,502",...,"7,792","8,072","8,457","9,291","10,565","8,444","5,783","4,471","3,417","2,482"
23,NaN,합계,"2,081","1,406","1,143","1,043","1,289","2,074","4,357","10,138",...,"16,037","16,367","16,989","18,405","20,892","15,041","10,139","7,789","5,798","4,142"
24,2010.01.09,입구,"1,044",775,589,581,750,"1,272","2,605","4,326",...,"10,033","9,994","9,988","9,851","8,090","5,349","4,044","3,282","2,240","1,622"
25,NaN,출구,"1,715","1,201",881,727,707,"1,004","1,957","3,735",...,"9,347","9,772","10,402","10,843","9,763","7,061","5,041","4,043","3,069","2,197"
26,NaN,합계,"2,759","1,976","1,470","1,308","1,457","2,276","4,562","8,061",...,"19,380","19,766","20,390","20,694","17,853","12,410","9,085","7,325","5,309","3,819"
27,2010.01.10,입구,"1,027",731,530,469,490,902,"1,890","2,760",...,"9,545","10,019","9,953","9,206","7,087","5,458","4,818","3,572","2,560","1,510"
28,NaN,출구,"1,503","1,066",814,581,447,641,"1,386","2,261",...,"7,967","8,918","9,634","9,987","8,495","6,320","5,304","4,169","3,183","2,171"
29,NaN,합계,"2,530","1,797","1,344","1,050",937,"1,543","3,276","5,021",...,"17,512","18,937","19,587","19,193","15,582","11,778","10,122","7,741","5,743","3,681"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"1,155",766,612,636,904,"1,520","3,474","7,535",...,"8,840","9,062","9,121","10,013","8,774","5,415","4,058","3,338","2,342","1,877"
1066,NaN,출구,"1,475","1,032",697,676,665,"1,179","2,653","6,015",...,"8,459","8,738","9,025","10,127","10,218","7,074","4,576","3,756","2,981","2,140"
1067,NaN,합계,"2,630","1,798","1,309","1,312","1,569","2,699","6,127","13,550",...,"17,299","17,800","18,146","20,140","18,992","12,489","8,634","7,094","5,323","4,017"
1068,2010.12.23,입구,"1,238",762,606,607,839,"1,554","3,522","7,757",...,"9,016","9,041","9,302","10,014","8,638","5,313","3,936","3,423","2,471","1,862"
1069,NaN,출구,"1,523","1,055",754,642,654,"1,239","2,854","5,820",...,"8,620","8,899","9,119","10,007","10,400","6,703","4,567","3,819","2,964","2,238"
1070,NaN,합계,"2,761","1,817","1,360","1,249","1,493","2,793","6,376","13,577",...,"17,636","17,940","18,421","20,021","19,038","12,016","8,503","7,242","5,435","4,100"
1071,2010.12.24,입구,"1,254",826,618,635,850,"1,464","3,202","6,806",...,"9,386","9,777","10,029","11,825","12,459","8,715","6,189","4,106","2,764","2,081"
1072,NaN,출구,"1,578","1,113",801,666,714,"1,110","2,508","5,417",...,"8,651","9,370","9,800","11,507","12,967","10,507","7,886","6,061","4,591","3,305"
1073,NaN,합계,"2,832","1,939","1,419","1,301","1,564","2,574","5,710","12,223",...,"18,037","19,147","19,829","23,332","25,426","19,222","14,075","10,167","7,355","5,386"
1074,2010.12.25,입구,"1,199",833,640,556,616,960,"1,842","2,875",...,"10,134","10,214","9,719","8,736","6,626","4,969","3,839","2,919","1,976","1,498"
1075,NaN,출구,"2,378","1,647","1,185",852,762,845,"1,399","2,432",...,"9,788","10,470","10,213","10,000","8,207","5,773","4,400","3,612","2,511","1,873"
1076,NaN,합계,"3,577","2,480","1,825","1,408","1,378","1,805","3,241","5,307",...,"19,922","20,684","19,932","18,736","14,833","10,742","8,239","6,531","4,487","3,371"
1077,2010.12.26,입구,838,562,449,347,377,639,"1,191","1,923",...,"10,936","11,173","10,962","7,899","5,417","4,112","3,421","2,477","1,555","1,262"
1078,NaN,출구,"1,381",909,677,493,400,449,927,"1,453",...,"8,449","9,477","9,882","9,030","5,981","5,516","4,499","4,411","2,887","1,718"
1079,NaN,합계,"2,219","1,471","1,126",840,777,"1,088","2,118","3,376",...,"19,385","20,650","20,844","16,929","11,398","9,628","7,920","6,888","4,442","2,980"
1080,2010.12.27,입구,689,457,386,502,784,"1,477","3,358","7,479",...,"7,936","7,795","7,621","7,721","7,081","4,371","3,190","2,670","1,990","1,402"
1081,NaN,출구,"1,219",741,519,449,504,858,"2,001","5,636",...,"8,023","8,074","8,086","8,417","8,369","5,401","3,794","3,058","2,383","1,756"
1082,NaN,합계,"1,908","1,198",905,951,"1,288","2,335","5,359","13,115",...,"15,959","15,869","15,707","16,138","15,450","9,772","6,984","5,728","4,373","3,158"
1083,2010.12.28,입구,961,684,506,585,765,"1,323","2,921","6,761",...,"8,684","8,512","8,177","8,587","7,522","4,278","3,175","2,713","1,946","1,384"
1084,NaN,출구,"1,222",853,681,559,619,973,"2,164","5,061",...,"8,192","8,668","8,724","9,041","8,508","5,784","4,006","3,133","2,511","1,758"
1085,NaN,합계,"2,183","1,537","1,187","1,144","1,384","2,296","5,085","11,822",...,"16,876","17,180","16,901","17,628","16,030","10,062","7,181","5,846","4,457","3,142"
1086,2010.12.29,입구,972,616,541,576,752,"1,216","2,553","6,256",...,"9,164","9,030","9,008","9,153","8,446","4,933","3,699","3,043","2,349","1,815"
1087,NaN,출구,"1,272",859,697,598,637,940,"1,915","4,835",...,"8,844","9,168","9,026","9,460","9,894","6,099","4,295","3,533","2,791","2,139"
1088,NaN,합계,"2,244","1,475","1,238","1,174","1,389","2,156","4,468","11,091",...,"18,008","18,198","18,034","18,613","18,340","11,032","7,994","6,576","5,140","3,954"
1089,2010.12.30,입구,"1,071",769,668,601,682,"1,088","2,308","5,243",...,"7,210","6,899","6,858","6,266","5,020","2,729","2,033","1,640","1,340","1,036"
1090,NaN,출구,"1,490",981,887,754,663,839,"1,726","4,074",...,"6,195","7,769","8,131","6,533","6,531","4,645","2,673","2,375","2,081","1,454"
1091,NaN,합계,"2,561","1,750","1,555","1,355","1,345","1,927","4,034","9,317",...,"13,405","14,668","14,989","12,799","11,551","7,374","4,706","4,015","3,421","2,490"
1092,2010.12.31,입구,739,502,412,418,481,664,"1,135","2,895",...,"8,495","8,948","8,825","8,426","7,260","5,095","3,585","2,623","1,866","1,360"
1093,NaN,출구,"1,098",764,581,538,527,666,"1,041","2,138",...,"7,897","8,822","9,160","9,341","9,104","6,815","5,333","4,097","3,433","2,447"
1094,NaN,합계,"1,837","1,266",993,956,"1,008","1,330","2,176","5,033",...,"16,392","17,770","17,985","17,767","16,364","11,910","8,918","6,720","5,299","3,807"

In [56]:
imsi_day = pd.DataFrame(dataset_jeonnam['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_jeonnam = dataset_jeonnam[(dataset_jeonnam.입출구 == '합계')]
dataset_jeonnam = dataset_jeonnam.reset_index()
del dataset_jeonnam['index']

In [57]:
del dataset_jeonnam['일자']
del dataset_jeonnam['입출구']

In [58]:
dataset_jeonnam = pd.concat([imsi_day, dataset_jeonnam], axis = 1)

In [59]:
day_time = []

for i in range(len(dataset_jeonnam)):
    for j in range(1,25):
        day_time.append(dataset_jeonnam.iloc[i][0] +'.' + dataset_jeonnam.columns[j])

In [60]:
car_time = []

for i in range(len(dataset_jeonnam)):
    for j in range(1,25):
        car_time.append(dataset_jeonnam.iloc[i][j])

In [61]:
dataset_jeonnam = pd.DataFrame({'시간' : day_time, '전남 교통량' : car_time })

In [62]:
dataset_jeonnam = dataset_jeonnam.set_index('시간')

In [63]:
dataset_jeonnam

                전남 교통량
시간
2010.01.01.00시   3,550
2010.01.01.01시   3,042
2010.01.01.02시   2,537
2010.01.01.03시   2,226
2010.01.01.04시   2,312
2010.01.01.05시   2,577
2010.01.01.06시   3,260
2010.01.01.07시   3,827
2010.01.01.08시   6,047
2010.01.01.09시   9,667
2010.01.01.10시  15,660
2010.01.01.11시  20,773
2010.01.01.12시  21,608
2010.01.01.13시  21,235
2010.01.01.14시  21,876
2010.01.01.15시  22,655
2010.01.01.16시  22,148
2010.01.01.17시  20,447
2010.01.01.18시  16,325
2010.01.01.19시  11,949
2010.01.01.20시   9,273
2010.01.01.21시   7,142
2010.01.01.22시   5,040
2010.01.01.23시   3,203
2010.01.02.00시   2,130
2010.01.02.01시   1,426
2010.01.02.02시   1,071
2010.01.02.03시     983
2010.01.02.04시   1,066
2010.01.02.05시   1,734
...                ...
2010.12.30.18시  11,551
2010.12.30.19시   7,374
2010.12.30.20시   4,706
2010.12.30.21시   4,015
2010.12.30.22시   3,421
2010.12.30.23시   2,490
2010.12.31.00시   1,837
2010.12.31.01시   1,266
2010.12.31.02시     993
2010.12.31.03시     956
2010.12.31.04시   1,008
2010.12.31.05시   1,330
2010.12.31.06시   2,176
2010.12.31.07시   5,033
2010.12.31.08시   8,039
2010.12.31.09시   7,557
2010.12.31.10시   9,157
2010.12.31.11시  10,708
2010.12.31.12시  12,038
2010.12.31.13시  13,802
2010.12.31.14시  16,392
2010.12.31.15시  17,770
2010.12.31.16시  17,985
2010.12.31.17시  17,767
2010.12.31.18시  16,364
2010.12.31.19시  11,910
2010.12.31.20시   8,918
2010.12.31.21시   6,720
2010.12.31.22시   5,299
2010.12.31.23시   3,807

[8760 rows x 1 columns]

# 전북권역

In [64]:
dataset_jeonbuk = pd.read_excel('car_jeonbuk_2010.xlsx')

In [65]:
dataset_jeonbuk

,일자,입출구,00시,01시,02시,03시,04시,05시,06시,07시,...,14시,15시,16시,17시,18시,19시,20시,21시,22시,23시
0,2010.01.01,입구,"1,236","1,187",920,624,583,743,"1,035","1,526",...,"9,226","9,419","8,811","7,697","5,719","4,670","3,657","2,681","1,916","1,328"
1,NaN,출구,"2,009","1,540","1,268","1,080","1,112","1,207","1,492","2,157",...,"9,894","10,316","10,173","9,074","7,385","5,391","4,057","2,990","2,080","1,382"
2,NaN,합계,"3,245","2,727","2,188","1,704","1,695","1,950","2,527","3,683",...,"19,120","19,735","18,984","16,771","13,104","10,061","7,714","5,671","3,996","2,710"
3,2010.01.02,입구,"1,038",873,407,384,536,721,"1,205","2,077",...,"11,396","11,278","9,922","8,034","5,968","4,734","3,477","2,806","2,134","1,563"
4,NaN,출구,"1,024",790,505,360,345,544,"1,011","2,336",...,"8,525","8,756","8,915","8,258","6,632","4,643","3,733","2,935","2,247","1,544"
5,NaN,합계,"2,062","1,663",912,744,881,"1,265","2,216","4,413",...,"19,921","20,034","18,837","16,292","12,600","9,377","7,210","5,741","4,381","3,107"
6,2010.01.03,입구,"1,143",879,379,305,401,608,"1,120","1,856",...,"9,427","9,284","8,519","7,422","5,287","4,028","3,601","2,923","2,125","1,564"
7,NaN,출구,"1,132",802,474,358,326,411,706,"1,395",...,"6,618","7,237","7,429","7,261","5,946","4,321","3,481","2,969","2,289","1,749"
8,NaN,합계,"2,275","1,681",853,663,727,"1,019","1,826","3,251",...,"16,045","16,521","15,948","14,683","11,233","8,349","7,082","5,892","4,414","3,313"
9,2010.01.04,입구,953,544,485,668,997,"1,552","2,440","4,054",...,"3,836","3,555","3,693","3,686","3,475","2,053","1,534","1,332","1,018",774
10,NaN,출구,"1,175",740,402,356,415,693,"1,571","3,887",...,"3,810","3,632","3,861","3,719","3,538","2,690","1,860","1,464","1,157",909
11,NaN,합계,"2,128","1,284",887,"1,024","1,412","2,245","4,011","7,941",...,"7,646","7,187","7,554","7,405","7,013","4,743","3,394","2,796","2,175","1,683"
12,2010.01.05,입구,559,458,462,462,512,541,939,"2,113",...,"3,917","3,834","3,828","3,930","3,698","2,096","1,583","1,396","1,153",869
13,NaN,출구,730,533,379,358,355,433,677,"1,880",...,"3,996","3,798","3,782","3,772","3,560","2,609","1,877","1,524","1,231",936
14,NaN,합계,"1,289",991,841,820,867,974,"1,616","3,993",...,"7,913","7,632","7,610","7,702","7,258","4,705","3,460","2,920","2,384","1,805"
15,2010.01.06,입구,662,512,460,510,551,718,"1,147","2,398",...,"4,819","4,828","4,816","4,942","4,404","2,616","2,063","11,027","1,385","1,070"
16,NaN,출구,703,519,344,280,310,496,842,"2,293",...,"4,715","4,848","4,571","4,372","4,189","3,168","2,334","1,837","1,536","1,108"
17,NaN,합계,"1,365","1,031",804,790,861,"1,214","1,989","4,691",...,"9,534","9,676","9,387","9,314","8,593","5,784","4,397","12,864","2,921","2,178"
18,2010.01.07,입구,869,594,546,586,701,830,"1,323","2,665",...,"5,339","5,332","5,239","5,481","4,777","2,927","2,218","1,912","1,574","1,185"
19,NaN,출구,844,627,431,348,388,588,"1,009","2,653",...,"5,083","5,285","4,963","4,755","4,559","3,593","2,527","2,129","1,627","1,357"
20,NaN,합계,"1,713","1,221",977,934,"1,089","1,418","2,332","5,318",...,"10,422","10,617","10,202","10,236","9,336","6,520","4,745","4,041","3,201","2,542"
21,2010.01.08,입구,939,650,615,611,741,926,"1,438","2,881",...,"5,943","6,314","6,301","7,231","7,246","4,479","3,194","2,552","1,926","1,455"
22,NaN,출구,956,713,468,358,375,617,"1,131","2,735",...,"5,866","6,011","5,855","6,147","6,387","5,878","4,436","3,512","2,903","2,162"
23,NaN,합계,"1,895","1,363","1,083",969,"1,116","1,543","2,569","5,616",...,"11,809","12,325","12,156","13,378","13,633","10,357","7,630","6,064","4,829","3,617"
24,2010.01.09,입구,"1,200",939,618,567,708,930,"1,575","2,619",...,"7,780","8,099","8,136","7,611","5,687","4,091","3,026","2,346","1,928","1,414"
25,NaN,출구,"1,501",980,721,519,473,745,"1,276","2,971",...,"7,147","8,245","8,348","7,917","6,733","5,170","3,887","3,182","2,569","1,717"
26,NaN,합계,"2,701","1,919","1,339","1,086","1,181","1,675","2,851","5,590",...,"14,927","16,344","16,484","15,528","12,420","9,261","6,913","5,528","4,497","3,131"
27,2010.01.10,입구,"1,037",961,399,350,374,558,"1,058","1,734",...,"8,299","8,182","7,918","7,236","5,330","3,893","3,239","2,598","1,846","1,478"
28,NaN,출구,"1,250",852,577,384,329,507,795,"1,889",...,"6,034","6,004","6,322","6,763","5,479","4,161","3,427","2,769","2,102","1,630"
29,NaN,합계,"2,287","1,813",976,734,703,"1,065","1,853","3,623",...,"14,333","14,186","14,240","13,999","10,809","8,054","6,666","5,367","3,948","3,108"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1065,2010.12.22,입구,"1,005",719,644,740,855,"1,177","2,077","3,749",...,"6,635","6,800","6,629","7,282","5,888","3,669","2,832","2,529","1,945","1,402"
1066,NaN,출구,"1,179",780,514,471,550,763,"1,775","4,009",...,"6,326","6,157","5,937","6,006","5,686","4,097","3,105","2,550","2,032","1,549"
1067,NaN,합계,"2,184","1,499","1,158","1,211","1,405","1,940","3,852","7,758",...,"12,961","12,957","12,566","13,288","11,574","7,766","5,937","5,079","3,977","2,951"
1068,2010.12.23,입구,"1,093",736,650,753,932,"1,270","2,080","3,610",...,"7,123","6,851","6,883","7,179","6,024","3,635","2,869","2,507","1,950","1,465"
1069,NaN,출구,"1,169",855,508,471,488,793,"1,614","3,989",...,"6,532","6,261","6,142","6,240","5,684","4,155","3,087","2,643","2,159","1,646"
1070,NaN,합계,"2,262","1,591","1,158","1,224","1,420","2,063","3,694","7,599",...,"13,655","13,112","13,025","13,419","11,708","7,790","5,956","5,150","4,109","3,111"
1071,2010.12.24,입구,"1,244",776,698,717,848,"1,049","1,860","3,293",...,"6,893","7,261","7,454","8,300","8,666","6,112","4,280","3,245","2,275","1,590"
1072,NaN,출구,"1,265",905,606,447,467,776,"1,515","3,625",...,"6,450","6,662","6,816","7,231","7,476","7,068","6,110","5,287","4,339","3,265"
1073,NaN,합계,"2,509","1,681","1,304","1,164","1,315","1,825","3,375","6,918",...,"13,343","13,923","14,270","15,531","16,142","13,180","10,390","8,532","6,614","4,855"
1074,2010.12.25,입구,"1,187",864,689,527,515,742,"1,176","1,920",...,"8,062","8,112","7,808","7,225","4,975","3,352","2,574","1,996","1,529","1,076"
1075,NaN,출구,"2,343","1,491",977,646,498,685,"1,023","2,169",...,"8,135","7,887","7,514","7,000","5,657","4,213","3,117","2,769","2,064","1,482"
1076,NaN,합계,"3,530","2,355","1,666","1,173","1,013","1,427","2,199","4,089",...,"16,197","15,999","15,322","14,225","10,632","7,565","5,691","4,765","3,593","2,558"
1077,2010.12.26,입구,740,558,346,293,299,402,760,"1,321",...,"9,539","9,595","8,044","5,848","4,144","3,210","2,326","1,866","1,361","1,016"
1078,NaN,출구,"1,046",733,441,299,289,375,571,"1,122",...,"5,826","5,552","5,942","6,255","5,789","4,541","3,625","2,609","1,816","1,274"
1079,NaN,합계,"1,786","1,291",787,592,588,777,"1,331","2,443",...,"15,365","15,147","13,986","12,103","9,933","7,751","5,951","4,475","3,177","2,290"
1080,2010.12.27,입구,742,541,520,622,776,"1,035","1,712","3,433",...,"6,146","5,588","5,587","5,590","4,655","2,842","2,282","1,957","1,503","1,130"
1081,NaN,출구,"1,019",857,636,492,456,541,"1,280","3,731",...,"5,437","5,259","5,160","4,991","4,604","3,241","2,494","2,030","1,694","1,286"
1082,NaN,합계,"1,761","1,398","1,156","1,114","1,232","1,576","2,992","7,164",...,"11,583","10,847","10,747","10,581","9,259","6,083","4,776","3,987","3,197","2,416"
1083,2010.12.28,입구,830,648,631,643,716,969,"1,685","3,112",...,"5,990","5,946","6,009","5,752","5,202","3,281","2,260","1,774","1,366","1,038"
1084,NaN,출구,931,725,522,391,404,570,"1,254","3,038",...,"5,557","5,742","5,581","5,112","4,822","3,914","2,781","2,283","1,695","1,215"
1085,NaN,합계,"1,761","1,373","1,153","1,034","1,120","1,539","2,939","6,150",...,"11,547","11,688","11,590","10,864","10,024","7,195","5,041","4,057","3,061","2,253"
1086,2010.12.29,입구,763,566,563,636,721,905,"1,527","3,179",...,"6,839","6,594","6,392","6,489","5,432","3,250","2,455","2,144","1,845","1,289"
1087,NaN,출구,"1,006",668,477,351,426,583,"1,157","2,954",...,"6,513","6,347","6,032","6,128","5,471","4,100","2,881","2,453","2,032","1,576"
1088,NaN,합계,"1,769","1,234","1,040",987,"1,147","1,488","2,684","6,133",...,"13,352","12,941","12,424","12,617","10,903","7,350","5,336","4,597","3,877","2,865"
1089,2010.12.30,입구,"1,003",780,689,628,641,826,"1,269","2,852",...,"5,875","5,589","5,162","5,065","4,380","2,462","1,816","1,449","1,167",953
1090,NaN,출구,"1,086",821,684,548,488,555,990,"2,616",...,"5,107","5,567","5,001","4,714","4,280","3,152","2,442","1,952","1,415","1,131"
1091,NaN,합계,"2,089","1,601","1,373","1,176","1,129","1,381","2,259","5,468",...,"10,982","11,156","10,163","9,779","8,660","5,614","4,258","3,401","2,582","2,084"
1092,2010.12.31,입구,671,617,501,502,555,619,997,"2,344",...,"6,877","6,901","7,150","7,527","6,478","4,546","3,280","2,558","1,962","1,334"
1093,NaN,출구,854,647,480,362,390,480,812,"2,266",...,"6,524","7,032","7,539","8,393","7,739","6,715","5,689","4,890","3,866","2,831"
1094,NaN,합계,"1,525","1,264",981,864,945,"1,099","1,809","4,610",...,"13,401","13,933","14,689","15,920","14,217","11,261","8,969","7,448","5,828","4,165"

In [66]:
imsi_day = pd.DataFrame(dataset_jeonbuk['일자'].dropna(axis = 0))
imsi_day = imsi_day.reset_index()
del imsi_day['index']
dataset_jeonbuk = dataset_jeonbuk[(dataset_jeonbuk.입출구 == '합계')]
dataset_jeonbuk = dataset_jeonbuk.reset_index()
del dataset_jeonbuk['index']

In [67]:
del dataset_jeonbuk['일자']
del dataset_jeonbuk['입출구']

In [68]:
dataset_jeonbuk = pd.concat([imsi_day, dataset_jeonbuk], axis = 1)

In [69]:
day_time = []

for i in range(len(dataset_jeonbuk)):
    for j in range(1,25):
        day_time.append(dataset_jeonbuk.iloc[i][0] +'.' + dataset_jeonbuk.columns[j])

In [70]:
car_time = []

for i in range(len(dataset_jeonbuk)):
    for j in range(1,25):
        car_time.append(dataset_jeonbuk.iloc[i][j])

In [71]:
dataset_jeonbuk = pd.DataFrame({'시간' : day_time, '전북 교통량' : car_time })

In [72]:
dataset_jeonbuk = dataset_jeonbuk.set_index('시간')

In [73]:
dataset_jeonbuk

                전북 교통량
시간
2010.01.01.00시   3,245
2010.01.01.01시   2,727
2010.01.01.02시   2,188
2010.01.01.03시   1,704
2010.01.01.04시   1,695
2010.01.01.05시   1,950
2010.01.01.06시   2,527
2010.01.01.07시   3,683
2010.01.01.08시   5,186
2010.01.01.09시   8,237
2010.01.01.10시  12,512
2010.01.01.11시  17,374
2010.01.01.12시  18,210
2010.01.01.13시  17,864
2010.01.01.14시  19,120
2010.01.01.15시  19,735
2010.01.01.16시  18,984
2010.01.01.17시  16,771
2010.01.01.18시  13,104
2010.01.01.19시  10,061
2010.01.01.20시   7,714
2010.01.01.21시   5,671
2010.01.01.22시   3,996
2010.01.01.23시   2,710
2010.01.02.00시   2,062
2010.01.02.01시   1,663
2010.01.02.02시     912
2010.01.02.03시     744
2010.01.02.04시     881
2010.01.02.05시   1,265
...                ...
2010.12.30.18시   8,660
2010.12.30.19시   5,614
2010.12.30.20시   4,258
2010.12.30.21시   3,401
2010.12.30.22시   2,582
2010.12.30.23시   2,084
2010.12.31.00시   1,525
2010.12.31.01시   1,264
2010.12.31.02시     981
2010.12.31.03시     864
2010.12.31.04시     945
2010.12.31.05시   1,099
2010.12.31.06시   1,809
2010.12.31.07시   4,610
2010.12.31.08시   7,175
2010.12.31.09시   6,712
2010.12.31.10시   8,430
2010.12.31.11시   9,816
2010.12.31.12시  10,309
2010.12.31.13시  11,992
2010.12.31.14시  13,401
2010.12.31.15시  13,933
2010.12.31.16시  14,689
2010.12.31.17시  15,920
2010.12.31.18시  14,217
2010.12.31.19시  11,261
2010.12.31.20시   8,969
2010.12.31.21시   7,448
2010.12.31.22시   5,828
2010.12.31.23시   4,165

[8760 rows x 1 columns]

In [74]:
dataset = pd.concat([dataset_seoul, dataset_gangwon, dataset_chungcheong, dataset_gyeongnam, dataset_gyeongbuk, dataset_jeonnam, dataset_jeonbuk], axis = 1)

In [75]:
dataset

                 서울 교통량  강원 교통량  충청 교통량  경남 교통량  경북 교통량  전남 교통량  전북 교통량
시간
2010.01.01.00시   48,664   9,629   9,168  18,680  12,775   3,550   3,245
2010.01.01.01시   49,703   8,890   8,243  16,902  12,158   3,042   2,727
2010.01.01.02시   37,651   8,296   6,313  13,599   9,581   2,537   2,188
2010.01.01.03시   24,362   8,943   5,346  10,731   7,980   2,226   1,704
2010.01.01.04시   21,250   9,176   4,963  11,067   8,094   2,312   1,695
2010.01.01.05시   25,866   9,435   5,603  13,901   9,170   2,577   1,950
2010.01.01.06시   34,342   9,496   6,985  16,756   8,792   3,260   2,527
2010.01.01.07시   46,212  10,914   9,384  18,669   9,874   3,827   3,683
2010.01.01.08시   61,214  17,646  14,315  28,909  16,498   6,047   5,186
2010.01.01.09시   81,427  20,077  20,783  42,148  25,855   9,667   8,237
2010.01.01.10시  112,769  26,014  30,825  59,758  38,301  15,660  12,512
2010.01.01.11시  139,873  30,977  37,554  72,002  47,604  20,773  17,374
2010.01.01.12시  144,359  31,688  36,775  73,095  47,534  21,608  18,210
2010.01.01.13시  139,629  32,104  36,152  71,840  46,760  21,235  17,864
2010.01.01.14시  140,010  32,714  38,707  81,356  48,609  21,876  19,120
2010.01.01.15시  143,754  32,969  39,786  75,013  49,831  22,655  19,735
2010.01.01.16시  142,949  33,973  38,613  75,000  49,231  22,148  18,984
2010.01.01.17시  131,935  31,647  36,238  70,095  46,529  20,447  16,771
2010.01.01.18시  113,274  26,036  30,689  58,450  38,682  16,325  13,104
2010.01.01.19시   94,244  20,235  23,359  47,088  30,753  11,949  10,061
2010.01.01.20시   89,302  15,176  19,413  39,333  25,147   9,273   7,714
2010.01.01.21시   83,758  11,219  16,148  33,888  19,840   7,142   5,671
2010.01.01.22시   68,898   8,498  11,829  24,654  14,400   5,040   3,996
2010.01.01.23시   49,567   5,723   7,870  16,294   9,346   3,203   2,710
2010.01.02.00시   31,953   3,729   5,247  11,258   6,039   2,130   2,062
2010.01.02.01시   19,146   2,746   3,426   7,038   3,895   1,426   1,663
2010.01.02.02시   12,912   1,975   2,300   5,221   2,659   1,071     912
2010.01.02.03시   10,854   1,715   1,956   4,424   2,163     983     744
2010.01.02.04시   12,659   1,835   2,388   4,843   2,611   1,066     881
2010.01.02.05시   21,139   2,276   3,657   7,904   4,245   1,734   1,265
...                 ...     ...     ...     ...     ...     ...     ...
2010.12.30.18시  141,172  13,139  32,997  63,838  37,391  11,551   8,660
2010.12.30.19시  108,964   9,255  23,161  48,276  26,036   7,374   5,614
2010.12.30.20시   84,214   6,904  16,795  37,504  18,699   4,706   4,258
2010.12.30.21시   75,217   5,634  13,553  30,601  14,846   4,015   3,401
2010.12.30.22시   66,897   4,564  10,651  23,818  11,592   3,421   2,582
2010.12.30.23시   52,666   3,508   7,597  18,164   8,291   2,490   2,084
2010.12.31.00시   39,358   2,513   5,731  13,364   6,029   1,837   1,525
2010.12.31.01시   28,629   1,784   4,090   9,316   4,170   1,266   1,264
2010.12.31.02시   21,148   1,337   3,225   6,648   3,115     993     981
2010.12.31.03시   16,899   1,263   2,996   5,279   2,660     956     864
2010.12.31.04시   17,284   1,353   3,436   5,747   2,931   1,008     945
2010.12.31.05시   28,006   1,697   4,583   9,950   4,682   1,330   1,099
2010.12.31.06시   67,060   2,987   8,925  24,448  10,409   2,176   1,809
2010.12.31.07시  124,142   6,263  23,290  58,883  26,922   5,033   4,610
2010.12.31.08시  138,612  10,569  30,792  61,495  31,839   8,039   7,175
2010.12.31.09시  124,551  10,884  25,302  54,315  28,500   7,557   6,712
2010.12.31.10시  131,012  13,542  28,039  59,037  32,822   9,157   8,430
2010.12.31.11시  132,699  16,364  29,980  60,471  34,532  10,708   9,816
2010.12.31.12시  131,153  17,700  30,420  57,906  33,274  12,038  10,309
2010.12.31.13시  139,056  19,902  34,923  61,629  37,088  13,802  11,992
2010.12.31.14시  150,214  21,697  38,772  67,860  41,760  16,392  13,401
2010.12.31.15시  158,151  22,374  41,275  69,108  44,308  17,770  13,933
2010.12.31.16시  169,089  24,106  43,889  73,521  46,948  17,985  14,689
2010.12.31.17시  174,131  24,703  46,084  79,053  50,415  17,767  15,920
2010.12.31.18시  167,454  23,944  46,100  73,920  48,253  16,364  14,217
2010.12.31.19시  149,686  20,528  36,815  63,496  42,195  11,910  11,261
2010.12.31.20시  130,923  17,084  28,978  51,897  34,104   8,918   8,969
2010.12.31.21시  111,106  14,972  23,266  45,840  26,875   6,720   7,448
2010.12.31.22시   91,608  12,871  17,823  36,947  21,447   5,299   5,828
2010.12.31.23시   65,084  10,953  12,174  24,514  15,323   3,807   4,165

[8760 rows x 7 columns]

In [76]:
dataset.to_csv('2010_car.csv')